### ISSUE TITLE
Administration Pagination Broken in every Page

### ISSUE THREAD

**Issue by DanPhyxius** [Sylius/Sylius#4211] opened 2016-02-18 12:03 UTC
Hi all,

first of all, thank you for this amazing framework, you guys have done a great job!

I found a critical bug on many views of administration zone and i saw that the bug exists in demo version too. Actually every view with paginations doesn't work.

<img width="1217" alt="schermata 2016-02-18 alle 13 02 21" src="https://cloud.githubusercontent.com/assets/4693301/13142794/e843104e-d63f-11e5-9c0f-7bfca40d6380.png">

Is there some fix that i could use for that?

Thanks a lot,
Dan

**Comment by DanPhyxius** [comment] 2016-02-18 14:16
Hi @pjedrzejewski ,

while I'm waiting for the final fix, could i ask you a quick to fix the problem? 
I would have some business urgency and I would be able to resolve that.

Thanks a lot for any answer,
Dan

**Comment by pjedrzejewski** [comment] 2016-02-18 14:29
@DanPhyxius Hey Dan! Looking into this right now. :) Thanks for reporting! I will get back to you with some feedback.

**Comment by DanPhyxius** [comment] 2016-02-18 14:50
We found a temporary fix, thanks a lot @pjedrzejewski! :+1:

**Comment by nakashu** [comment] 2016-02-18 15:17
@DanPhyxius please share :)

**Comment by DanPhyxius** [comment] 2016-02-18 16:54
@nakashu It's just a temporary raw workaround for the Products Pagination, i think it would be better to get a true fix for that :)

**Comment by pjedrzejewski** [comment] 2016-02-18 17:22
I added a test case for API - https://github.com/Sylius/Sylius/pull/4216/files, seems like it is problem only with HTML version or perhaps specific to how Sylius uses ResourceBundle. I will investigate further and hopefully fix it in admin too...

**Comment by xantrix** [comment] 2016-02-18 17:32
it seems related to setting the correct current page query param to the PagerFanta paginator as it is already being done on https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourcesCollectionProvider.php#L60 for all resources without a specific Repository like http://demo.sylius.org/administration/countries/?page=2

**Comment by pjedrzejewski** [comment] 2016-02-18 17:37
@xantrix You are right, working on a fix right now. The issue is that we do not handle paginator correctly if it is returned from a custom method. :) Thanks!

**Comment by xantrix** [comment] 2016-02-18 17:39
you're welcome @pjedrzejewski ;)

**Comment by pjedrzejewski** [comment] 2016-02-18 18:05
Should be fixed when #4216 is merged. Thanks for reporting!

**Comment by michalmarcinkowski** [comment] 2016-02-18 19:02
Should be fixed now.

**Closed by michalmarcinkowski** 2016-02-18 19:02 UTC
Labels: Bug, Critical

**Comment by Pitoune** [comment] 2017-08-18 13:23
hi guys, I think the issue is not closed. The fixed you made works fine for API but it does not work for grid. I have open a PR to fix issue in grid.
