### ISSUE TITLE
[Order] Current state of order state machine integration?

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5365] opened 2016-06-27 11:49 UTC
Hi, I am trying to do some work based on the order state by implementing state subscribers.

Currently I don't think the state transitions happen on cancel, abandon, etc? Only on `OrderTransitions::CREATE` ? I can't see a way to transition an order from the 0.19 admin,

Is this a WIP or am I missing something?

**Comment by pjedrzejewski** [comment] 2016-06-27 12:42
I will close this as duplicate of #5366, because it all boils down to wrong implementation of state resolver and other state manipulating services.

**Closed by pjedrzejewski** 2016-06-27 12:42 UTC
