### ISSUE TITLE
Exception when adding route to a page

### ISSUE THREAD

**Issue by ojhaujjwal** [Sylius/Sylius#2741] opened 2015-05-18 07:16 UTC
![image](https://cloud.githubusercontent.com/assets/4995501/7675869/4c218d3c-fd5d-11e4-89f9-3e78cf6f0e55.png)

![image](https://cloud.githubusercontent.com/assets/4995501/7675873/56e77074-fd5d-11e4-8a77-48e93c493253.png)

![image](https://cloud.githubusercontent.com/assets/4995501/7675874/5f95ca2c-fd5d-11e4-90a4-2e3d9175b2e6.png)

**Comment by psyray** [comment] 2015-05-18 08:07
Duplicate of https://github.com/Sylius/Sylius/issues/2696

**Comment by aRn0D** [comment] 2015-05-21 22:35
@ojhaujjwal I close it because another issue is already opened.

**Closed by aRn0D** 2015-05-21 22:35 UTC
