### ISSUE TITLE
 taxonomy bundle as a stand-alone bundle

### ISSUE THREAD

**Issue by dimduj** [Sylius/Sylius#3366] opened 2015-09-28 11:21 UTC
Hello,

I'm stuck using the taxonomy bundle as a stand-alone bundle for a project..
Any clues on how to setup this bundle properly ?

Here is my config.yml:

`
sylius_taxonomy:
  driver: doctrine/orm # Configure the doctrine orm driver used in documentation.
  classes:
    taxonomy:
      model: Sylius\Component\Taxonomy\Model\Taxonomy
      controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
      repository: ~
      form: Sylius\Bundle\TaxonomiesBundle\Form\Type\TaxonomyType
    taxon:
      model: Sylius\Component\Taxonomy\Model\Taxon
      controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
      repository: ~
      form: Sylius\Bundle\TaxonomiesBundle\Form\Type\TaxonType
  validation_groups:
    taxonomy: [sylius]
    taxon: [sylius]

stof_doctrine_extensions:
  orm:
    default:
      tree: true
      sluggable: tr
`

The error is : 
                                                                                           
  [Symfony\Component\Config\Definition\Exception\InvalidTypeException]                           
  Invalid type for path "sylius_taxonomy.classes.taxonomy.form". Expected array, but got string 

My kernel app : 

 public function registerBundles()
    {
        $bundles = array(
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Symfony\Bundle\AsseticBundle\AsseticBundle(),

            new FOS\RestBundle\FOSRestBundle(),
            new JMS\SerializerBundle\JMSSerializerBundle($this),
            new Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle(),

            new Sylius\Bundle\TaxonomyBundle\SyliusTaxonomyBundle(),
            new Sylius\Bundle\ResourceBundle\SyliusResourceBundle(),

            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),

I think it might be related to documentation : https://github.com/Sylius/Sylius/issues/3247#event-405346765 but any guidance will be appreciate :)

**Comment by next-sentence** [comment] 2015-09-29 09:06
taxonomy:
    form:
        default: Sylius\Bundle\TaxonomiesBundle\Form\Type\TaxonomyType

**Comment by gperdomor** [comment] 2015-09-30 22:07
<pre><code>
taxonomy:
    form:
        default: Sylius\Bundle\TaxonomiesBundle\Form\Type\TaxonomyType
</code></pre>

**Comment by michalmarcinkowski** [comment] 2015-10-01 21:21
Duplicate of https://github.com/Sylius/Sylius/issues/3247#event-405346765. If you still have problems please continue there.

**Closed by michalmarcinkowski** 2015-10-01 21:21 UTC
Labels: Bug, Documentation
