### ISSUE TITLE
UUIDs instead of IDs for identifying database records

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#1655] opened 2014-06-26 10:35 UTC
Hi,

Why did you guys choose to prefer incremental integer `IDs` over `UUIDs`? I think using an  UUID will be beter when sharding databases etc. It will be much easier to implement and you are assured that every record is unique regardless the environment.

What do you guys think about this? I could create a PR for this. @pjedrzejewski @umpirsky

**Comment by michalmarcinkowski** [comment] 2015-10-01 21:34
@steffenbrem I think you can override the doctrine mapping and after https://github.com/Sylius/Sylius/issues/3379 merge (as I said in https://github.com/Sylius/Sylius/issues/3379) you could use `UUID` instead of `IDs`. For import/export functionality we would use unique `code`.

**Comment by michalmarcinkowski** [comment] 2015-12-11 12:59
Duplicate of https://github.com/Sylius/Sylius/issues/3379

**Closed by michalmarcinkowski** 2015-12-11 12:59 UTC
Labels: RFC
