### ISSUE TITLE
[ApiBundle][Checkout] Transition hold does not exist on object Sylius\\Component\\Core\\Model\\OrderItemUnit with graph sylius_shipment_unit

### ISSUE THREAD

**Issue by ylastapis** [Sylius/Sylius#5667] opened 2016-08-01 14:45 UTC
This errors occured when calling for the finalize step with PUT

```PUT /api/checkouts/{{orderId}}```

following the checkout full process here : [http://docs.sylius.org/en/latest/api/checkouts.html](http://docs.sylius.org/en/latest/api/checkouts.html)

Comes from https://github.com/Sylius/Sylius/pull/5606/files which removed the "hold" transition, I suppose...

**Comment by ylastapis** [comment] 2016-08-02 08:59
Disabling the events fixes the problem, but that's not a solution. I try to understand how the "hold" state works :)

```
        <service id="sylius.listener.order_inventory" class="%sylius.listener.order_inventory.class%">
            <argument type="service" id="sylius.order_processing.inventory_handler" />
            <!--<tag name="kernel.event_listener" event="sylius.checkout.finalize.pre_complete" method="holdInventoryUnits" />-->
            <tag name="kernel.event_listener" event="sylius.order_item.pre_create" method="resolveInventoryState" priority="-100" />
            <tag name="kernel.event_listener" event="sylius.order_item.pre_update" method="resolveInventoryState" priority="-100" />
        </service>
```

and 

```
        <service id="sylius.listener.order_shipping" class="%sylius.listener.order_shipping.class%">
            <argument type="service" id="sylius.order_processing.shipment_processor" />
            <argument type="service" id="sylius.processor.shipment_processor" />
            <tag name="kernel.event_listener" event="sylius.checkout.shipping.initialize" method="processOrderShipments" />
            <!--<tag name="kernel.event_listener" event="sylius.checkout.finalize.pre_complete" method="updateShipmentStatesOnhold" />-->
        </service>
```

**Comment by ylastapis** [comment] 2016-08-26 12:09
reworked here https://github.com/Sylius/Sylius/pull/5896

**Comment by steffenbrem** [comment] 2016-09-09 22:59
This should be re-opened since it is still an issue. It is caused by the following state machine callback: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine.yml#L152

**Comment by ylastapis** [comment] 2016-09-12 06:40
The second one have been fixed, it seems. 
It still get the error on the first one : 

```
        <service id="sylius.listener.order_inventory" class="%sylius.listener.order_inventory.class%">
            <argument type="service" id="sylius.order_processing.inventory_handler" />
            <tag name="kernel.event_listener" event="sylius.checkout.finalize.pre_complete" method="holdInventoryUnits" />
            <tag name="kernel.event_listener" event="sylius.order_item.pre_create" method="resolveInventoryState" priority="-100" />
            <tag name="kernel.event_listener" event="sylius.order_item.pre_update" method="resolveInventoryState" priority="-100" />
        </service>
```

**Comment by steffenbrem** [comment] 2016-09-12 09:57
@ylastapis I've submitted a possible fix. I don't think the cascading is needed anymore so I removed it all together. Let's see! 😄

**Comment by ylastapis** [comment] 2016-09-13 09:58
@steffenbrem I confirm that you PR is fixing the problem :)
But you should check travis, it's failing for some weird reason oO

**Comment by steffenbrem** [comment] 2016-09-13 11:16
Oh yeah probably bad luck, i've restarted it seems like it will pass now, hopefully 😛

**Comment by steffenbrem** [comment] 2016-09-14 11:49
@michalmarcinkowski Could you maybe look into my PR and see if it could get merged?

**Closed** 2016-09-14 20:27 UTC
Labels: Bug
