### ISSUE TITLE
Include shipping costs into base for tax calculation

### ISSUE THREAD

**Issue by madc** [Sylius/Sylius#2450] opened 2015-02-11 12:33 UTC
The tax calculator is only called, when a item is added to the cart. Later during the checkout, this previously calculated values are used. I'd need a way to include the shipping costs into the tax calculation. Would be great to have a checkbox, to handle this in backend. This feature should also be desirable for other people when building B2B e-commerce solutions based on sylius.

**Comment by pjedrzejewski** [comment] 2015-12-11 14:51
Duplicate of #605.

**Closed by pjedrzejewski** 2015-12-11 14:51 UTC
