### ISSUE TITLE
Variant option values are not selected while editing variants.

### ISSUE THREAD

**Issue by GrandLTU** [Sylius/Sylius#10262] opened 2019-03-25 15:13 UTC
**Sylius version affected**: 1.1.6 and up

**Description**  
Might be the same as #1178
`ProductOptionValueCollectionType` expects that product option values will arrive in same order as options defined in product which is not always the case (e.g. when importing products) and that deselects actual values when entering variant edit.

**Steps to reproduce**  
- Have a configurable product with at least two options
- Add ProductOptionValue's in reverse order compared to product configuration
- Enter variant edit form in admin  

**Possible Solution**  
Instead of setting property path here https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ProductBundle/Form/Type/ProductOptionValueCollectionType.php#L51 add model transformer:
```php
        $builder->addModelTransformer(
            new CallbackTransformer(
                function ($model) {
                    if (false === \is_array($model)) {
                        return [];
                    }

                    $norm = [];
                    /** @var ProductOptionValueInterface $value */
                    foreach ($model as $value) {
                        $norm[$value->getOptionCode()] = $value;
                    }

                    return $norm;
                },
                function ($norm) {
                    if (false === \is_array($norm)) {
                        return [];
                    }

                    return array_values($norm);
                }
            )
        );
        $builder->addModelTransformer(new CollectionToArrayTransformer());
```

**Comment by Zales0123** [comment] 2019-03-26 07:55
Hello @GrandLTU, do you think it's the same issue that is resolved by https://github.com/Sylius/Sylius/pull/9223?

**Comment by pamil** [comment] 2019-03-26 14:43
Thanks for reporting, it looks like a duplicate of #8999, could you confirm?

**Comment by GrandLTU** [comment] 2019-03-26 16:38
Yes looks like it is

**Comment by lchrusciel** [comment] 2019-03-29 08:07
Closing as a duplication of #8999

**Closed by lchrusciel** 2019-03-29 08:07 UTC
Labels: Bug
