### ISSUE TITLE
Infinite loop when viewing admin

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#6984] opened 2016-12-02 07:02 UTC
I haven't been able to figure this out for the past hour, but I am getting into an infinite loop when viewing the admin dashboard. I tailed the error logs, and it seems to be the translation layer getting into an infinite loop.

The whole shop bundle seems fine, as my whole store is functioning.

Information:

- I am on master (current HEAD)
- Only happens in admin
- Currently crashing at the first translation on the page, which is for the title

Really strange bug report, let me know if I could provide with anything else.

**Comment by pjedrzejewski** [comment] 2016-12-02 07:05
Have you tried clearing cookies?

**Comment by inssein** [comment] 2016-12-02 07:09
@pjedrzejewski yeah I tried incognito as well

**Comment by michalmarcinkowski** [comment] 2016-12-02 07:17
Can't reproduce... try clearing cache also.

**Comment by inssein** [comment] 2016-12-02 07:18
@michalmarcinkowski @pjedrzejewski I found the issue, but don't know how to fix it.

It seems to be the `ThemeAwareTranslator`. When I return the input in `transformLocale`, it works fine.

**Comment by michalmarcinkowski** [comment] 2016-12-02 07:37
You use themes? Can you tell me more about your store configuration?

**Comment by inssein** [comment] 2016-12-02 07:40
Yeah - I decided to use themes in order to override all the shop styles instead of overriding the bundle. So I only have one theme, and I set the channel to use that theme.

Not sure what other configuration would be relevant. I also use semantic ui very differently than you guys, I actually checked out the project so I can override their less variables.

**Comment by NeverResponse** [comment] 2017-01-27 09:53
No matter what configuration i try, still can't reproduce.
Think this can be closed as it seems to be an extreme edge case (if at all).
/cc @michalmarcinkowski

**Closed** 2017-01-27 10:51 UTC
Labels: Potential Bug
