### ISSUE TITLE
[ResourceBundle] Problem with the Doctrine repository `find` method override

### ISSUE THREAD

**Issue by yann-eugone** [Sylius/Sylius#2656] opened 2015-04-14 07:38 UTC
Hi all, I had a problem with user authentification (base issue can be found [here](https://github.com/symfony/symfony/issues/14334)).

The problem was the find method of my User repository inherited form the [Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository](https://github.com/Sylius/SyliusResourceBundle/blob/master/Doctrine/ORM/EntityRepository.php#L43).

My solution is the following : 

```php
public function find($id)
{
    if (is_array($id)) {
        $identifier = key($id);
        $value      = reset($id);
    } else {
        $identifier = $this->getClassMetadata()->getIdentifier()[0];
        $value      = intval($id);
    }

    return $this
        ->getQueryBuilder()
        ->andWhere(sprintf('%s.%s = %d', $this->getAlias(), $identifier, $value))
        ->getQuery()
        ->getOneOrNullResult()
        ;
}
```

**Comment by stof** [comment] 2015-08-02 00:38
Note that this solution still has drawbacks. It does not work for entities using a compound key (i.e. an identifier based on several fields).

Btw, overwriting ``EntityRepository::find`` without adding any additional feature (AFAICT at least) is a bad idea: the default implementation of finding an entity by its primary key is optimized to avoid performing a DB query in case the object is already in the unit of work of the entity manager, as the object is already known (and would be returned after performing your DB query anyway)

**Comment by yann-eugone** [comment] 2015-08-03 07:23
Understood.
But considering the base issue, this is still a problem...

And still, the base method as the same drawbacks :

```php
public function find($id)
{
    return $this
        ->getQueryBuilder()
        ->andWhere($this->getAlias().'.id = '.intval($id))
        ->getQuery()
        ->getOneOrNullResult()
    ;
}
```

Do you have any idea on what we could do to fix this ?

**Comment by stof** [comment] 2015-08-03 09:00
@yann-eugone I know. The issue is in Sylius itself

**Comment by wpottier** [comment] 2015-08-12 15:42
The main issue (override of find behavior) is present in the DocumentRepository (mongodb-odm driver) too with the same impact on authentication.

**Comment by pjedrzejewski** [comment] 2015-08-13 09:13
I have refactored how repositories work in #2255 and we no longer do these custom calls. Standard ``find`` will be called. Stay tuned for the fix being merged soon. :)

**Comment by michalmarcinkowski** [comment] 2016-10-10 14:50
Fixed already.

**Closed by michalmarcinkowski** 2016-10-10 14:50 UTC
Labels: Feature Request, Has PR
