### ISSUE TITLE
Error create new route

### ISSUE THREAD

**Issue by amoraru** [Sylius/Sylius#2894] opened 2015-06-18 13:08 UTC
A "__toString()" method was not found on the objects of type "Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent" passed to the choice field. To read a custom getter instead, set the option "property" to the desired property path.

**Comment by coudenysj** [comment] 2015-07-07 20:32
Duplicate of #2883.

**Comment by michalmarcinkowski** [comment] 2015-07-28 14:31
Fixed by https://github.com/Sylius/Sylius/pull/2952

**Closed by michalmarcinkowski** 2015-07-28 14:31 UTC
Labels: Bug
