### ISSUE TITLE
ChoiceList is Deprecated ...:(

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3029] opened 2015-07-16 11:33 UTC
Deprecated since version 2.7, to be removed in 3.0.
            Use {@link \Symfony\Component\Form\ChoiceList\ArrayChoiceList} instead.

**Comment by pjedrzejewski** [comment] 2015-12-09 15:33
Duplicate of #3032.

**Closed by pjedrzejewski** 2015-12-09 15:33 UTC
