### ISSUE TITLE
Issues using only some bundles

### ISSUE THREAD

**Issue by pyrech** [Sylius/Sylius#2480] opened 2015-02-17 15:53 UTC
Hi,

After installing 4 bundles (Product, Cart, Order, Promotion), I got those issues:

```
ServiceNotFoundException in vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php line 58:
The service "sylius.repository.product" has a dependency on a non-existent service "sylius.context.locale".
```

Looks like requiring and registering the LocaleBundle fixed this issue. Maybe a forgetten dependency?

The second issue is related to Doctrine Mapping. Running `app/console doctrine:schema:update --force` throws an exception:
```
[Doctrine\ORM\Mapping\MappingException]
The target-entity Sylius\Component\Core\Model\Coupon cannot be found in 'Sylius\Component\Promotion\Model\Promotion#coupons'.
```
Why does it try to load from the Core component (which is obviously not installed)?

Thanks in advance for any help.

**Comment by adamelso** [comment] 2015-02-28 22:30
I've raised a PR to address the first issue in #2528

Meanwhile this can be resolved by adding `sylius/locale-bundle` to your composer.json, adding `new Sylius\Bundle\LocaleBundle\SyliusLocaleBundle(),` to your AppKernel.php and adding `sylius_locale: { driver: doctrine/orm }`  to your config.yml. Docs will also be updated for the Product Bundle.

**Comment by pyrech** [comment] 2015-02-28 23:02
Thank you! In the final, we did not use Sylius so I will not be able to confirm any fix.
Anyway, I hope you will be able to reproduce and fix the second issue ;)

**Comment by pamil** [comment] 2015-09-02 09:34
Couldn't reproduce second issue, I guess it have been fixed in the meantime :) @pjedrzejewski @michalmarcinkowski I think it can be closed.

**Closed** 2015-09-02 09:40 UTC
Labels: Blocker, Bug, Easy Pick
