### ISSUE TITLE
Wrong cart items total if promotion on units

### ISSUE THREAD

**Issue by Roshyo** [Sylius/Sylius#11585] opened 2020-06-16 09:31 UTC
**Sylius version affected**: 1.7 for sure, and I believe all previous as well

**Description**  
We have a cart composed of 3 quantities of 1 product, $100 each.
If we apply a promotion of 100 split among those units, we will have
* Unit1: 100 - 34
* Unit2: 100 - 33
* Unit3: 100 - 33

Everything is good from amount perspective, but in the cart summary, we end up having something like this :
![image (11)](https://user-images.githubusercontent.com/9363039/84757583-9c5cce00-afc4-11ea-9e12-42527bef586f.png)

The Order total is right, but since each `Beige Strappy summer dress` costs `$71.40`, the items total is wrong.
In fact, those `Beige Strappy summer dress` costs `$71.40`, `$71.39` and `$71.39`

**Steps to reproduce**  
Apply a different promotion to first unit of an order item with multiple units and go to cart page.

**Possible Solution**  
This has something to do with the way item total and itemsTotal are calculated.

**Comment by Roshyo** [comment] 2020-09-21 06:51
Do not stale please

**Comment by laurentdabbb** [comment] 2021-12-08 10:11
Hi,

Please consider this as a bug.

**Bug is on the getSubtotal() method on OrderItem**. 
This method return ```$this->getDiscountedUnitPrice() * $this->quantity;```

The problem is that **getDiscountedUnitPrice()** only retrieve discounted price from the **first** orderItem unit.

I encountered same issue with a new custom type of promotion "percentage discount on the Nth cheapest article".
This promotion allow to purpose promotion operations like "2+ 1 free".
With this promotion, I apply a 100% discount adjustment on cheapest unit. If this unit is the first unit of an orderItem, getSubtotal method return 0 whereas other units on this orderItem are not free...

**Comment by NoResponseMate** [comment] 2023-06-16 12:09
Hi @Roshyo

It seems the bug has been fixed in 1.11 via #14090
Let me know if that's not the case, but for now, I'm closing this issue.

Cheers 🍻

**Closed by NoResponseMate** 2023-06-16 12:09 UTC
Labels: Bug
