### ISSUE TITLE
[Bug] Cannot enable a channel for a product after new channel added

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#7081] opened 2016-12-14 09:24 UTC
While working on #7079 I found this bug.

**Steps to reproduce:**
- Clean install
- Load default fixtures
- Go to admin
- Create a new channel (FR Web Store)
- Go to products page
- Click edit in a product with variants 
- Enable channel FR Web Store
- Save
- The attached error shows up
- Reload page, the channel is still disabled

<img width="1278" alt="captura de pantalla 2016-12-14 a las 10 17 14" src="https://cloud.githubusercontent.com/assets/1749891/21176429/fa2a87fe-c1e6-11e6-890b-f3f577b3affc.png">

**Tested in:**
- demo.sylius.org
- Locally on commit `130c38f4b630f4404fbe7a84e7194583793372d7` Dec 13 21:43

**Comment by michalmarcinkowski** [comment] 2016-12-14 09:51
In order to enable product in given channel you have to specify the price in this channel for all variants of this product. We will work on a better and more precise validation error.

**Comment by pjedrzejewski** [comment] 2016-12-14 10:09
@michalmarcinkowski This is a bug.

**Comment by michalmarcinkowski** [comment] 2016-12-14 10:24
Depending on what you call "bug". From definition: 
> A software bug is an error, flaw, failure or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways.

What happens now is intended behaviour. We have a validation that works and prevents system from incorrect state, but the problem is with the UI since it produces a lot of not clear errors instead of a single one "You cannot enable product for channel before you fill in price for all its variants". 

The product can't be assigned to a channel when the price for all its variants is not filled in, that is a platform requirement not a bug. Nevertheless I don't mind putting `bug` label :)

**Comment by inspiran** [comment] 2016-12-15 06:29
I concur with @pjedrzejewski ; a customer would perceive this as a bug.   It would be pointless to argue against ;-)  

That being said, the validation should also display which variants are causing an issue.   If you would want it to make customer friendly (not just developer friendly) it would be better to provide a price list alike view that allows you to alter prices for all variants in one view.

**Comment by michalmarcinkowski** [comment] 2017-01-17 12:59
Fixed in https://github.com/Sylius/Sylius/pull/7135.

**Closed by michalmarcinkowski** 2017-01-17 12:59 UTC
Labels: Bug, Documentation, UI
