### ISSUE TITLE
Ordering Taxons (making use of the Repository methods for gedmo:tree)

### ISSUE THREAD

**Issue by petesiss** [Sylius/Sylius#783] opened 2014-01-06 17:37 UTC
Taxons make use of the Nested Set behaviour extension for Doctrine. 

As far as I can tell they use the Gedmo extension which is documented [here](https://github.com/l3pp4rd/DoctrineExtensions/blob/master/doc/tree.md).

However, they don't use the Repository class ``Gedmo\Tree\Entity\Repository\NestedTreeRepository``, which means methods useful for e.g. reordering taxons amongst their siblings are unavailable.

How would it be possible to make use of these methods?

The Taxon Repository defined by the service ``sylius.repository.taxon`` is ``Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository``, which obviously doesn't make sense to extend the Gedmo NestedTreeRepository.

My drive in investigating this is to be able to manage the order of Taxons. It seems to make the most sense to use the NestedTree lft / rgt etc to do this, because the Taxon entity definition already looks like it tries to do this [here] (https://github.com/Sylius/SyliusTaxonomiesBundle/blob/master/Resources/config/doctrine/model/Taxon.orm.xml#L38), with:

    <order-by>
            <order-by-field name="left" direction="DESC" />
     </order-by>

So this seems like a logical thing to pursue, rather than implementing a new sort_order field.

**Comment by pjedrzejewski** [comment] 2015-12-14 13:25
Duplicate of #2312. Let's keep the discussion there.

**Closed by pjedrzejewski** 2015-12-14 13:25 UTC
Labels: Support Request
