### ISSUE TITLE
Change local in shop don't work

### ISSUE THREAD

**Issue by lasotaartur** [Sylius/Sylius#7655] opened 2017-03-02 13:41 UTC
Steps to reproduce

1. Add locale in Configuration -> Locales in admin
2. Select old and new locale in channel in Configuration -> Channels -> Edit (first one) -> Locales in admin
3. Change default locale to new locale in shop - default locale is still selected

I tested it on dev-master

**Comment by pjedrzejewski** [comment] 2017-03-02 13:58
I swear I was playing with the app today and it worked just fine. :/

**Comment by pamil** [comment] 2017-03-02 14:00
I just have checked it out and I couldn't reproduce it.

**Comment by lasotaartur** [comment] 2017-03-03 09:37
It works. :)

**Comment by michalmarcinkowski** [comment] 2017-03-03 10:38
Closing then 😉

**Closed by michalmarcinkowski** 2017-03-03 10:38 UTC
Labels: Potential Bug
