### ISSUE TITLE
[AdminBundle] Product isn't displaying if the translation for the current locale is missing

### ISSUE THREAD

**Issue by jakubtobiasz** [Sylius/Sylius#13296] opened 2021-11-16 15:58 UTC
**Sylius version affected**: As far as I know - all versions
**Description**  

If the product has not defined translation for the current locale it isn't displayed on the products list in AdminPanel.

Let's say we have 2 active locales in our shop en_US and pl_PL. We have defined translations for the both locales for the all products. We want to add de_DE locale. We add de_DE locale in AdminPanel, hire the translator and set his AP language to Germany (cause he's German :D). He goes `/admin/products` and sees nothing. The product list is empty.

**Steps to reproduce**  

The easiest way: 
1. Check your shop locales
2. Change your AP language to anyone not defined in the locales list
3. Go to `/admin/products`

**Possible Solution**  

The solutions is pretty simple. In `Sylius\Bundle\CoreBundle\Doctrine\ORM\ProductRepository::createListQueryBuilder` the translation is joined using `innerJoin`. The result is empty list if product title for the current locale is missing. I've managed to fix this by changing `innerJoin` to `leftJoin`.

The only problem I've found is the empty `Name` column in case of not defined title for the current locale. I'm considering the following solutions:
a) If there's no title for the current locale just display '-' - ugly but works, and still better than no products displayed
b) Add some text (?) informing there's no translation for your locale - a lot of work with translating for all supported languages
c) Remove `Name` column (:D) - a little drastic way, but at the end of the day I think it would be the best solution. In my opinion it's enough for a Shop Admin to have Product's code to identify the right product.

I can prepare the PR fixing this problem (it's almost done btw) but I would like to ask you to share your thoughts what would be the best way to deal with `Name` column in that case.

**Comment by jakubtobiasz** [comment] 2022-01-06 08:08
@Zales0123 Hi, would you mind take a look and try to help me choose a right solution for this problem?

I can fix this but I'd like to hear your opinion before I start to prevent doing the same job twice 👊🏻.

**Comment by lchrusciel** [comment] 2022-01-26 19:22
Hey Jakub! 

It would be superb to have this fix finally in codebase! I'm wondering how much impact will this have for the code and performance. We can skip later until we will provide some tooling for that. The first part is more important. I can see, that we've been using leftjoin until 2017. You can find this change 
![image](https://user-images.githubusercontent.com/6213903/151231234-7120f66a-a4ff-48e5-bdab-2226dde2bb49.png)
in this PR: https://github.com/Sylius/Sylius/pull/7647/

The problem is, that we didn't provide any tests back then. Perhaps reverting this change may be a good step forward. However, I would start with a reproduction scenario, so we can be sure that we are fixing the correct stuff. Then, let's try your proposal and see if the build is green. 

According to the `Name` column issue. Sylius was meant to print default translation in such a case and this is behaviour I would expect. The strange thing is that it should work like this right now. This is something, that we should cover with a scenario as well.

**Comment by jakubtobiasz** [comment] 2022-01-27 18:36
> According to the Name column issue. Sylius was meant to print default translation in such a case and this is behaviour I would expect. The strange thing is that it should work like this right now. This is something, that we should cover with a scenario as well.
I've checked this and it does... only if translation for the fallback language is provided... :D.

![CleanShot 2022-01-27 at 6 35 35@2x](https://user-images.githubusercontent.com/80641364/151412926-683a7aeb-a05f-4834-a8cf-4108b59e8a55.png)
![CleanShot 2022-01-27 at 6 36 18](https://user-images.githubusercontent.com/80641364/151413010-4b1bb0c9-21b4-478d-b76f-c2cac13cc16f.png)

Without any change (except leftJoin instead innerJoin):
<img width="960" alt="CleanShot 2022-01-27 at 6 37 38@2x" src="https://user-images.githubusercontent.com/80641364/151413278-818dc588-1a47-45f1-a5a1-7aec2153aece.png">

Translations collection is empty so there's no translation we can fallback to. Getting a default locale is also pretty painful. Getting by relation even if possible with one channel it's harder with more.

---

Replacing `innerJoin` with `leftJoin` seems to be the only solution, even at the expense of performance.  If you worry about performance we can always introduce feature toggle.
```
sylius_admin:
    product_grid:
        show_only_for_current_locale: true # or something like that, just an initial idea
```

Then
```
        if (/* feature on */) {
            $queryBuilder
                ->leftJoin('o.translations', 'translation')
            ;
        }
        
        if (/* feature off */) {
            $queryBuilder
                ->innerJoin('o.translations', 'translation', 'WITH', 'translation.locale = :locale')
                ->setParameter('locale', $locale)
            ;
        }
```

The solution from `feature on` fails on PHP 8.0/Symfony 5.4/Mysql5.4 and 8.0 but on only 3 steps. Beside these 3 steps everything seems to work as expected. As it loads all locales it has an access to fallback one. I don't think the performance would be really significantly  affected by this change. What do you think @lchrusciel?

I have `en_UG` locale and product's name translation fallbacks to `en_US`.
<img width="774" alt="CleanShot 2022-01-27 at 7 20 38@2x" src="https://user-images.githubusercontent.com/80641364/151420047-79a0c40b-2237-4a1f-b84b-8fd109db780b.png">

**Comment by vvasiloi** [comment] 2022-01-27 22:12
How about this: https://github.com/Sylius/Sylius/issues/13134#issuecomment-925715024

If not, then there's another solution: remove `->addSelect('translations')` and hydrate the translations afterwards or just let Doctrine do it on the fly.

**Comment by rimas-kudelis** [comment] 2022-02-07 06:47
> How about this: [#13134 (comment)](https://github.com/Sylius/Sylius/issues/13134#issuecomment-925715024)

I don't feel like it's even a question worth asking. I'd say that bug is a duplicate of this one, and it's pretty obvious that admin's preferred locale should not act as an automatic filter of what that admin sees.

**Comment by jakubtobiasz** [comment] 2022-02-07 07:50
@vvasiloi I feel my question is more like ask "which way is preferred" 😅. Maybe in a few days I'm going to try generate more product data and check the performance.

**Comment by vvasiloi** [comment] 2022-02-07 07:56
@jakubtobiasz the preferred way is the one with best performance. It would be great If you could do a test with at least 100k products, otherwise just wait for me to do it, but I keep moving it from one day to another on my todo list. 😞

**Comment by rimas-kudelis** [comment] 2022-02-07 08:08
> Translations collection is empty so there's no translation we can fallback to. Getting a default locale is also pretty painful. Getting by relation even if possible with one channel it's harder with more.

I don't think you can guarantee that there will always be a translation in the default locale, can you?

> Replacing `innerJoin` with `leftJoin` seems to be the only solution, even at the expense of performance. If you worry about performance we can always introduce feature toggle.
> 
> ```
> sylius_admin:
>     product_grid:
>         show_only_for_current_locale: true # or something like that, just an initial idea
> ```
> 
> Then
> 
> ```
>         if (/* feature on */) {
>             $queryBuilder
>                 ->leftJoin('o.translations', 'translation')
>             ;
>         }
>         
>         if (/* feature off */) {
>             $queryBuilder
>                 ->innerJoin('o.translations', 'translation', 'WITH', 'translation.locale = :locale')
>                 ->setParameter('locale', $locale)
>             ;
>         }
> ```

I'd suggest something different: a toggle to "only select current locale" (if a toggle is necessary at all), which would mean that in both cases a left join would be used, but with `feature off` all translations would be selected automatically, and with `feature on`, only the "active" translation, or whatever you may want to call it. In both cases all products would be visible in the list, but with `feature on` some products would potentially be shown without titles.

Then again, the maximum rows you can get at once by default is 50, right? Even if you have 10 translations per product, that doesn't seem like too many extra rows in the result (500) and since an FK is involved, it shouldn't affect performance in any significant way.

**Comment by vvasiloi** [comment] 2022-02-07 08:53
> I don't think you can guarantee that there will always be a translation in the default locale, can you?

In normal conditions, when using the AP to add the translation, there's a validation for that.
However, one can add the translation without using the AP and validation.

**Comment by rimas-kudelis** [comment] 2022-02-07 09:00
Also, you can probably change your default locale midway, so "a translation in some locale will certainly exist" is just a grounded assumption at best.

**Comment by vvasiloi** [comment] 2022-02-15 16:20
> By design, in Sylius there should always be default locale defined - the one configured as parameter in app.

That doesn't mean the resource has a translation in the default locale.
It can be missing when:
1. The default locale is changed and the resource has no translation for the new one
2. The resource was created bypassing the validation that requires a translation for the default locale

**Comment by vvasiloi** [comment] 2022-02-15 17:00
It's fine as long as the solution doesn't make that assumption.
For the performance test, it also matters a lot how many translations the products have (multiple locales).

**Comment by lchrusciel** [comment] 2022-02-17 11:00
So, folks, I've tested proposals given proposals and sample solutions you may found in related PoCs. 

I've run performance tests for following numbers:

Amount of | Amount
-- | --
Products: | 100k
Products per page: | 50
Iterations in profile: | 10
Translations per product: | 8

Here are numbers: 
Profile | Total time | Network time | Memory usage | Amount of queries
-- | -- | -- | -- | --
 Reference build | 1.1 s | 562 ms | 32.9 MB | 500 ms / 134 rq
 Reference build with sorting  | 4.04 s | 3.46 s | 32.9 MB | 3.16 s / 134 rq
 Reference build with filtration | 4.61 s | 4.25 s | 31.9 MB  | 3.91 s / 54 rq
 Profile with leftjoin | 813 ms | 511 ms | 16.6 MB  | 456 ms / 54 rq
 Profile with leftjoin with sorting | 1.4 s  | 1.08 s | 16.6 MB  | 985 ms / 54 rq
 Profile with leftjoin with filtration | 1.18 s | 880 ms | 16.6 MB  | 784 ms / 54 rq
 Profile with leftjoin and different admin locale | 1.16 s | 833 ms | 16.7 MB  | 747 ms / 75 rq
 Profile with leftjoin and different admin locale with sorting | 3.13 s | 2.81 s | 16.7 MB  | 2.54 s / 75 rq
 Profile with leftjoin and different admin locale with filtration | 2.79 s | 2.49 s | 16.6 MB  | 2.24 s / 75 rq
 Profile with lazy translations | 833 ms | 502 ms | 27.3 MB  | 446 ms / 54 rq
 Profile with lazy translations with sorting | 1.35 s | 1 s    | 27.3 MB  | 902 ms / 54 rq
 Profile with lazy translations with filtration | 1.25 s | 920 ms | 27.2 MB  | 834 ms / 54 rq
 Profile with lazy translations and different admin locale | 411 ms | 151 ms | 27.5 MB | 133 ms / 95 rq
 Profile with lazy translations and different admin locale with sorting | 2.93 s | 2.58 s | 27.6 MB  | 2.34 s / 75 rq
 Profile with lazy translations and different admin locale with filtration | 2.72 s | 2.38 s | 27.6 MB  | 2.15 s / 75 rq

So the conclusion is, that both solutions have better performance, but lazy translations wins. The problem is, that both solutions would introduce the regression, because it won't correctly sort products in not default locale. This is already covered by following scenarios:

https://github.com/Sylius/Sylius/blob/56bf4199f4c63e0c9101b1e3eb42bd5e4553583a/features/product/managing_products/sorting_products.feature#L50-L65

In addition, we should write a new scenarios, how it should behave with missing translations for both sorting and filtering. My stand is that, we cannot remove "name" field, nor skip sorting and filtering features. I don't see any possibility how to provide mentioned features for lazy translations, however I'm almost sure that it is possible with some custom translation join. Perhaps someone will prove me wrong. 

So, for anyone who is willing to pick it from here, what is required to solve the issue:
1. All current tests must work as they did already
2. Write new scenarios and have them approved by @CoderMaggie

**Comment by jakubtobiasz** [comment] 2022-02-20 12:05
@lchrusciel

I was thinking over this problem. I think left join/any other of mentioned options are not an exact solution. E.g. left joining just solves the problem with not appearing products but doesn't solve problem with empty name column. We have `sylius_locale.locale` which under the hood is an alias to `locale` property which should be considered as a default locale (at least in my opinion).

While configuring a grid we can pass `sylius_locale.locale`.

`src/Sylius/Bundle/AdminBundle/Resources/config/grids/product.yml`:
```yaml
sylius_grid:
    grids:
        sylius_admin_product:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: 
                            - expr:service('sylius.context.locale').getLocaleCode()
                            - expr:parameter('sylius_locale.locale')
                            - $taxonId
 ```

In repository we can get this value and use it while joining translations.  Using `or` user's locale is favored but in case it's not present in translation the default one from `sylius_locale.locale` is used. Tests are passing and it seems it works as expected.
`src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php`:
```php
    public function createListQueryBuilder(string $locale, string $defaultLocale, $taxonId = null): QueryBuilder
    {
        $queryBuilder = $this->createQueryBuilder('o')
            ->addSelect('translation')
            ->innerJoin(
                'o.translations',
                'translation',
                'WITH',
                'translation.locale = :locale OR translation.locale = :defaultLocale'
            )
            ->setParameter('locale', $locale)
            ->setParameter('defaultLocale', $defaultLocale)
        ;

        if (null !== $taxonId) {
            $queryBuilder
                ->innerJoin('o.productTaxons', 'productTaxon')
                ->andWhere('productTaxon.taxon = :taxonId')
                ->setParameter('taxonId', $taxonId)
            ;
        }

        return $queryBuilder;
    }
```

What do you think @lchrusciel?

**Comment by lchrusciel** [comment] 2022-02-21 13:03
If it works, let's go with it. What you've described is exactly, what we want to achieve. We still need to cover new cases sorting and filtering for mixed translation, but that should be manageable. Can you open a PR with your proposal, so we can see the build? 

Nonetheless, I'm wondering what is the change between your proposal and mine (#13653) that your works and mine not (despite fact, that I hardcoded `en_US`)

**Closed** 2022-03-24 16:17 UTC
Labels: Admin, Bug
