### ISSUE TITLE
[Roadmap] Price and original price by date

### ISSUE THREAD

**Issue by ping86** [Sylius/Sylius#9990] opened 2018-12-03 09:38 UTC
Sometimes you use price and original price in products to show a product discount in the product page. The problem is if you have a product in promotion until 13 of september, you must change this price manually.

I think sylius must have a field "Price valid at", and disable this special price automatically.

Thanks.

**Comment by Prometee** [comment] 2019-01-08 11:03
In the same way, it would be cool if we can customize price by currency.
But in that case we have to add a currency slug to all the URLs because a product page with one URL could not display two differents prices at the same time.

**Comment by lchrusciel** [comment] 2019-01-08 11:58
Price and original price by date means you are expecting catalog promotions feature. It's an entirely valid use case, but not supported by Sylius core.

Let's be clear: Price and the original price is just a helper field, that may be used like this. Further improvements are up to you. 

There were several attempts to solve this issue. You may check these for inspiration:
https://github.com/Locastic/SyliusCatalogPromotionPlugin (/cc @antonioperic)
https://github.com/Snake-Tn/SyliusCatalogPromotionPlugin
https://github.com/URBANARA/UrbanaraCatalogPromotionPlugin

Of course, one day we may pick this topic up. Or you can create/help to improve one of existent(but probably not production ready) solutions.

**Comment by CoderMaggie** [comment] 2019-11-15 12:29
Closing as duplicate of #9851

**Closed by CoderMaggie** 2019-11-15 12:29 UTC
Labels: Enhancement, Roadmap
