### ISSUE TITLE
[Taxation] Wrong tax shipping calculator in OrderShipmentTaxesApplicator

### ISSUE THREAD

**Issue by bigboss86** [Sylius/Sylius#12484] opened 2021-03-26 14:32 UTC
**Sylius version affected**: 1.9

**Description**  
In the OrderShipmentTaxesApplicator, the tax amount should be calculated based on the shipping adjustment of the order and not on shipment.

**Steps to reproduce**  
Add a tax rate in a shipping method and try to complete the checkout.

**Possible Solution**  
Get order adjustments type shipping instead of shipment adjustment total.

**Comment by CoderMaggie** [comment] 2022-07-12 12:16
Hi Damian!

It seems you might be misunderstanding where the adjustments are applied. The Taxes calculation should be using the data from Shipment instead of Order as this is where we hold all the adjustments related to the Shipment (including discounts).

The ShippingChargesProcessor is responsible for adding all the adjustments related to Shipments on the Shipment.

Could you elaborate more? Are you getting some wrong results while calculating the taxes? Could you provide us with more data, ideally some scenarios?

**Comment by NoResponseMate** [comment] 2023-06-16 12:14
Hi @bigboss86 

Since this issue had no further updates and we're still missing details on what exactly is the problem and how to reproduce it I'm closing this.
If you think this is indeed a bug and can provide any lead for us to reproduce it, let me know and I'll reopen it.

Cheers 🍻

**Closed by NoResponseMate** 2023-06-16 12:14 UTC
Labels: Potential Bug, Shop
