### ISSUE TITLE
LoadORMMetadataSubscriber breaks non-Sylius entity relationships when using ResourceBundle within an existing project

### ISSUE THREAD

**Issue by kriswillis** [Sylius/Sylius#3103] opened 2015-08-04 10:41 UTC
I'm integrating some Sylius bundles into an existing project and it appears as though the LoadORMMetadataSubscriber is unsetting a number of my existing entities' relationships.

**Comment by jimbocoder** [comment] 2015-08-05 01:17
I've been using the ResourceBundle to create my own non-Sylius resource entities and mixing them with Sylius resources and haven't come across this issue.  Can you provide more details and/or try to demonstrate the bug?

**Comment by kriswillis** [comment] 2015-08-05 09:04
In this specific instance, I'm using the Sulu CMF (https://github.com/sulu-io/sulu-standard) as the base for a project and attempting to implement (initially) the ProductBundle from Sylius; ResourceBundle is a dependency of that and has this Doctrine subscriber that is killing all of the relationships on Sulu's entities (that are mapped super classes). As these entities are not managed by the ResourceBundle, presumably, the relationships are not reinstated at a later stage? I haven't looked in to how all of this is supposed to work…

It looks like I can get around this for the time being by telling the `loadClassMetadata` method to only affect Sylius entities with something like:

```php
if (strpos($metadata->namespace, 'Sylius') !== 0) {
    return;
}
```

I don't know what implications this may have going forward, but at least for now, the project isn't throwing errors all over the place.

**Comment by gperdomor** [comment] 2015-08-05 12:51
Your bundles extends AbstractResourceBundle?, because in that case you need change the mapping files to Resources/config/doctrine/model/, or override the protected function getModelNamespace to return the directory which contains the mapping files.

**Comment by jimbocoder** [comment] 2015-08-05 15:05
I've been having success just overriding this one method:

```php
class OnnitQABundle extends AbstractResourceBundle
{
    public static function getSupportedDrivers()
    {
        return array(SyliusResourceBundle::DRIVER_DOCTRINE_ORM);
    }
}
```

If these suggestions don't help, see if you can come up with a reproducible case, or possibly move this to stackoverflow if it becomes more of a support discussion than a bug.

**Comment by kriswillis** [comment] 2015-08-05 15:33
This isn't an issue with it interfering with my own entities, it's messing with entities in third party bundles. For example, there's the third-party SuluSecurityBundle with a user and group entity, the relationship between them is unset upon adding the SyliusResourceBundle to my kernel.

**Comment by pjedrzejewski** [comment] 2015-12-09 15:22
This should be fixed now if occurred. Please reopen if you still have this issue.

**Closed by pjedrzejewski** 2015-12-09 15:22 UTC
Labels: Bug
