### ISSUE TITLE
[Storage] CookieStorage provider not working properly

### ISSUE THREAD

**Issue by MichaelMackus** [Sylius/Sylius#2615] opened 2015-03-23 19:39 UTC
Seems as though the cart cookie isn't being set properly (or even used - see: https://github.com/Sylius/Sylius/pull/2089#issuecomment-62068728).

I've tried setting invalidate_session: false and setting sylius_cart storage provider to the "cookie" storage. I then added a listener to the kernel response to set the cookie manually there. But the cart is still not working properly with the CookieStorage provider.

**Comment by steffenbrem** [comment] 2015-03-26 10:32
I had this issue too. See this link: https://github.com/Sylius/Sylius/pull/2089#issuecomment-62068728

**Comment by pjedrzejewski** [comment] 2015-12-11 12:52
Duplicate of #3009.

**Closed by pjedrzejewski** 2015-12-11 12:52 UTC
Labels: Bug
