### ISSUE TITLE
Percentage promotion decimal rounding

### ISSUE THREAD

**Issue by JordivdB** [Sylius/Sylius#11977] opened 2020-10-30 10:29 UTC
**Sylius version affected**: 1.7.7

**Description**  
When filling in the coupon and choosing a percentage. When you fill in something like 2,5 it stores as 0.025 in the database, thats how it supposed to be. But when reopening the promotion page it shows as 2, and saving it again will round it down to 0.02 in the database. Seems like a rounding issue somewhere while fetching the data to show?

**Steps to reproduce**  
See description above.

**Possible Solution**  
Might need to re-consider the rounding of percentages while pulling data to view.

**Comment by lchrusciel** [comment] 2020-11-02 19:50
Hey @JordivdB,

thanks for reporting an issue. Seems like a rounding error is placed somewhere in Symfony percentage form if I understood your issue correctly. Would you like to give it a try and fix it?

**Comment by maxmishyn** [comment] 2022-11-07 17:20
It looks like that the same issue is now is in the catalog promotions' percentage discounts. I found the reason of it there CoreBundle/CatalogPromotion/Calculator/PercentageDiscountPriceCalculator.php -> calculate method.
It simply casts result of the calculation to the int what just drops off decimal part.

**Comment by NoResponseMate** [comment] 2023-06-16 12:23
Hi @JordivdB 

It's been a while, but I can confirm that this is indeed a bug that still occurs.
We've added it to our backlog and should be fixed in the near future.

Cheers 🍻

**Closed** 2023-08-03 11:20 UTC
Labels: Bug
