### ISSUE TITLE
[Locale][WebBundle] Locales based on channel not work

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#3284] opened 2015-09-17 01:41 UTC
Hi, i notice someting weird.

Sylius can detect the channel using the hostname and a <code>like</code> criteria (maybe should use <code>equal</code>, but that is not the point of this issue), every channel have some <code>locales</code>, but when you open sylius in the browser and go to any channel, i get a little problem with the translations.

Use case: I have 3 channels with the following locales:
    - Channel 1: <code>es_VE</code> and <code>en_US</code>
    - Channel 2: <code>es_CO</code> and <code>en_US</code>
    - Channel 3: only <code>en_US</code>

When open sylius on any channel, the locale menu is fine, but the locale used in the view is the default locale <code>es_VE</code>, even when the Channel 2 and 3 aren't associate to that locale

**Comment by pamil** [comment] 2015-09-25 14:45
Couldn't reproduce your issue, what's your Sylius version? Could you write down the exact steps to reproduce it?

**Comment by gperdomor** [comment] 2015-09-30 21:57
@pamil v0.15.0, i will try with v0.16.0

**Comment by gperdomor** [comment] 2015-10-28 22:48
@pjedrzejewski confirmed, the bug is present on master branch

**Comment by michalmarcinkowski** [comment] 2015-10-28 23:38
@gperdomor could you write the exact steps to reproduce this issue?

**Comment by gperdomor** [comment] 2015-10-29 00:03
Of course.

1 - Load fixtures.
2 - Edit <code>WEB-US</code> channel and change the <code>url</code> field to <code>us.sylius.local</code> or whatever you want, and select some <code>locales</code>, in my case i use <code>en_US - English</code> and <code>it_IT - Italian</code>
3 - Edit <code>WEB-UK</code> channel and change the <code>url</code> field to <code>ve.sylius.local</code> (I use <code>ve</code> prefix to simulate Venezuelan channel) and select some <code>locales</code>, in my case i use <code>en_Es - Spanish</code>
4 - When i open the first url (WEB-US channel), all text are in english, it's ok i guess (i don't know if this is because my browser and SO are in english or because show english by default)
5 - When i open the other url (The spanish channel), i expect to see all text in Spanish (or another language configured in the channel), but in my case i still see the text in English.

I think this happen because <code>LocaleSubscriber</code> is not using the ChannelAwareLocaleProvider</code>.

**Comment by gperdomor** [comment] 2015-10-29 00:12
I forgot, when you edit the channels, you will get an error if try to open <code>sylius.local</code> because the url match with more than one channel, maybe we should use <code>equal</code> and not <code>like</code> sentence to match the url

**Comment by michalmarcinkowski** [comment] 2016-09-15 17:51
Fixed on master.

**Closed by michalmarcinkowski** 2016-09-15 17:51 UTC
Labels: Awaiting Feedback, Bug
