### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Currency "EUR" is not available.") in "SyliusWebBundle:Backend/Order:_form.html.twig" at line 96

### ISSUE THREAD

**Issue by nicolasricci** [Sylius/Sylius#3181] opened 2015-08-25 15:16 UTC
And the EUR code exists in the sylius_currency table ... 

Any idea?

**Comment by pjedrzejewski** [comment] 2015-08-27 15:58
Hi Nicolas!

Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius

**Comment by nicolasricci** [comment] 2015-08-27 16:12
Well, I believe there is something wrong with the CurrencyConverter. I have managed a dirty fix and I will try and make a PR if I find a better way

**Comment by pjedrzejewski** [comment] 2015-08-28 12:10
@nicolasricci Great, thank you! :+1:

**Comment by michalmarcinkowski** [comment] 2015-08-28 15:15
Reopeing, since it is an issue...

**Comment by michalmarcinkowski** [comment] 2015-08-30 13:28
@nicolasricci could you explain us the issue? Maybe we will figure out the proper fix together :wink:

**Comment by nicolasricci** [comment] 2015-09-01 10:41
order.currency in returns the full Currency object in my case in {{ item.total|sylius_price(order.currency) }} so this is crashing the test in the CurrencyConverter.
I have fixed it with

```
$currency = is_string($code) ? $this->getCurrency($code) : $code;
```
but I have now another issue since I cannot update the payment state of my order as it says the product "does not have sufficient stock." when it is not the case. 

Will update you on the situation when I have more.

**Comment by nicolasricci** [comment] 2015-09-01 10:45
Well actually I had a value "on_hold" for this product so this is why I had the insufficient stock message when updating.
Let me know if you want me to commit a PR to fix the other issue

**Comment by michalmarcinkowski** [comment] 2015-12-11 15:34
Duplicate of https://github.com/Sylius/Sylius/issues/1686

**Closed by michalmarcinkowski** 2015-12-11 15:34 UTC
Labels: Bug
