### ISSUE TITLE
bug(Cart): Cart random adjustments total desynchronization

### ISSUE THREAD

**Issue by SVillette** [Sylius/Sylius#12070] opened 2020-11-20 11:31 UTC
**Sylius version affected**: 1.8

**Description**  
Desynchronization of order total with adjustments. 
In my example, cart total calculation is being wrong for an unknown reason.
Possible reason : items total is lower than shipping total

**Steps to reproduce**  
- Using `included in price` tax rates (Don't know if it is related but it affect adjustments). It means that the only non neutral adjustment is type `shipping`
- Having a cart with 2 products for a total of 8.30€
- Selected shipping method of 9.99€
- For some reason calculation have been wrong one time and order total have been set to 830 and total adjustment to 0.
- After debugging order processors, when shipping adjustment are being removed of order, order total adjustment have -999 value. So when order total is recalculated, it is been set to 0.

**Debugging values**
- At the beginning of `CompositeOrderProcessor`, order values are :
    - Total : 830
    - Items total : 830
    - Adjustments total : 0
- At the beginning of `CompositeOrderProcessor`, adjustments present are:
    - shipping type, 999, 0 (non neutral)
    - tax type, 167, 1 (neutral)

- Then adjustments are removed in `OrdeAdjustmentsClearer` (before recalculation), so order values are :
    - Total : 830
    - Items total : 830
    - Adjustments total : -999

- Then adjustments are removed in `OrdeAdjustmentsClearer` (after recalculation), so order values are :
    - Total : 0
    - Items total : 830
    - Adjustments total : -999

**Possible Solution**  
One way to resolve this is to call `$order->recalculateAdjustmentsTotal();` at the beginning of `Sylius\Component\Core\OrderProcessing\OrdeAdjustmentsClearer::process` so adjustments total is synchronized before removing adjustments and calculate total.

**Comment by SVillette** [comment] 2021-05-14 07:22
Hi @nemoneph 

Yes, I created a new OrderProcessor that I tagged with `sylius.order_processor` that call this unique function and added a high priority (Sylius order processors have priorities from 0 to 50).
Our ecommerce is not online yet, but I did not see any more bugs on this side.

```yaml
  app.processor.order_adjustments_clearer:
    class: App\Service\Order\Processor\OrderAdjustmentsRecalculator
    tags:
      - { name: sylius.order_processor, priority: 70 }
    public: true
```

**Comment by nemoneph** [comment] 2021-05-17 07:30
@SVillette Thx, will try this.

**Comment by jakubtobiasz** [comment] 2023-07-14 14:07
Hello @SVillette 👋🏼!
It took us some time, but do you have any information whether this bug is still a case for Sylius `1.12`? I wasn't able to reproduce it, but it might be due to the randomness of the issue (as @nemoneph mentioned, he had 2 cases of 4000 orders). 

We might consider implementing the recalculator with a really high priority (to make sure it will always be executed as the last one), but I'd like to get any feedback before :D.

**Comment by SVillette** [comment] 2023-07-14 14:21
Hi @jakubtobiasz !
As I mentionned in my last comment, I added a new processor that recaculate adjustments. This processor is the first to be called.

```php
class OrderAdjustmentsRecalculator implements OrderProcessorInterface
{
    public function process(OrderInterface $order): void
    {
        $this->recalculateOrderAdjustmentsTotal($order);
    }

    private function recalculateOrderAdjustmentsTotal(OrderInterface $order): void
    {
        foreach ($order->getItems() as $item) {
            $this->recalculateOrderItemAdjustmentsTotal($item);
        }

        $order->recalculateAdjustmentsTotal();
    }

    private function recalculateOrderItemAdjustmentsTotal(OrderItemInterface $orderItem): void
    {
        foreach ($orderItem->getUnits() as $unit) {
            $unit->recalculateAdjustmentsTotal();
        }

        $orderItem->recalculateAdjustmentsTotal();
    }
}
```

We started our project with Sylius 1.4, I don't know what version of Sylius was when I first opened the issue but with that processor it seems fixed now.
Sorry to not giving you much more context, I didn't investigate more on this issue.

**Comment by SVillette** [comment] 2023-07-14 14:22
Hi @jakubtobiasz !
As I mentionned in my last comment, I added a new processor that recaculate adjustments. This processor is the first to be called.

```php
class OrderAdjustmentsRecalculator implements OrderProcessorInterface
{
    public function process(OrderInterface $order): void
    {
        $this->recalculateOrderAdjustmentsTotal($order);
    }

    private function recalculateOrderAdjustmentsTotal(OrderInterface $order): void
    {
        foreach ($order->getItems() as $item) {
            $this->recalculateOrderItemAdjustmentsTotal($item);
        }

        $order->recalculateAdjustmentsTotal();
    }

    private function recalculateOrderItemAdjustmentsTotal(OrderItemInterface $orderItem): void
    {
        foreach ($orderItem->getUnits() as $unit) {
            $unit->recalculateAdjustmentsTotal();
        }

        $orderItem->recalculateAdjustmentsTotal();
    }
}
```

We started our project with Sylius 1.4, I don't know what version of Sylius was when I first opened the issue but with that processor it seems fixed now.
Sorry to not giving you much more context, I didn't investigate more on this issue.

**Comment by jakubtobiasz** [comment] 2023-07-20 16:01
Hello @SVillette 👋🏼

Thanks for sharing your solution, but as it's hard or nearly impossible to reproduce it, we decided to close this issue. If anyone finds this kind of issue on their side, they'll be able to fix it with the order processor provided by you.

For now, we don't want to add a potentially dead code, as we are not event sure this resolves the problem, or if it stopped occurring.

I hope you understand our decision 🖖🏻.

**Closed by jakubtobiasz** 2023-07-20 16:01 UTC
Labels: Potential Bug
