### ISSUE TITLE
CartCollector throws 'No locale has been set and current locale is undefined' exception with new Doctrine option

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#17316] opened 2024-10-23 13:09 UTC
**Sylius version affected**: 1.12

**Description**  
I have this doctrine configuration:

```yaml
# config/packages/doctrine.yaml
doctrine:
    orm:
        enable_lazy_ghost_objects: true
```

When those are enabled the `\Sylius\Bundle\CoreBundle\Collector\CartCollector` will trigger an exception like this:

![image](https://github.com/user-attachments/assets/8d4db4cc-6d7d-4586-84ba-3c430519bee4)

Notice that it's a circular exception, but I figured out that it works when I set `enable_lazy_ghost_objects` to false.

I don't have much to go on here, and it may not be a bug in Sylius, but now I've reported it at least :|

**Comment by NoResponseMate** [comment] 2024-10-24 12:55
Hi Joachim 👋 ,

It's a known issue, at least it popped up on [ResourceBundle](https://github.com/Sylius/SyliusResourceBundle/issues/901) some time ago.
AFAIR there's is no fix as of yet, but a solution proposal was opened in the meanwhile.

Some more refs:
- https://github.com/doctrine/DoctrineBundle/issues/1809
- https://github.com/doctrine/orm/issues/11524
- https://github.com/doctrine/orm/pull/11544

Unfortunately, I don't know if we can actually do anything about it on our side since the problem apparently lies inside ORM's ProxyFactory 😕

**Comment by GSadee** [comment] 2024-12-05 14:00
Hi! I am closing the issue as the problem is not on our side and we are unable to fix it here.

**Closed as completed by GSadee** 2024-12-05 14:00 UTC
Labels: Dependencies, Bug
