### ISSUE TITLE
Removing child product taxons in taxons tree

### ISSUE THREAD

**Issue by czende** [Sylius/Sylius#9799] opened 2018-10-08 11:33 UTC
**Sylius version affected**: 1.*

**Description**  
When you check some child or subchild taxon, save product form and then check another random taxon **without** expanding previous parent taxon, previous child taxon disappears.

**Steps to reproduce**  
1. Set product taxon to mugs-child:
![screenshot 2018-10-08 at 13 27 10](https://user-images.githubusercontent.com/5628485/46606579-f4f47c00-cafd-11e8-8bcf-d3e4169c86dc.png)

2. Save product
3. Set product taxon to T-shirts **without** expanding Mugs taxon:
![screenshot 2018-10-08 at 13 27 27](https://user-images.githubusercontent.com/5628485/46606599-105f8700-cafe-11e8-855c-781b21a4607b.png)
4. Save product
5. See that mugs-child taxon is no longer checked:
![screenshot 2018-10-08 at 13 27 34](https://user-images.githubusercontent.com/5628485/46606626-25d4b100-cafe-11e8-8304-e249eb4ef992.png)

**Comment by pamil** [comment] 2018-10-09 14:14
Will be published in next patch release :) Duplicate of #9365.

**Closed by pamil** 2018-10-09 14:14 UTC
Labels: Admin, Bug
