### ISSUE TITLE
different locale in admin and shop

### ISSUE THREAD

**Issue by samanmohamadi** [Sylius/Sylius#7822] opened 2017-03-23 20:17 UTC
I use different locale in admin(EN) and shop(fa_IR), So all taxons needs to be  created in fa_IR locale .
the problem is when I want to choose a taxon for a product it search and shows me only taxons in EN locale, because the locale of sylius context in admin is EN.
I think locale should not be involved in searching for resources in admin.

**Comment by aistis-** [comment] 2017-04-26 14:25
Hi @samanmohamadi how do you set a different locale for the admin? Thanks

**Comment by pjedrzejewski** [comment] 2017-08-31 12:51
Duplicate of #8225.

**Closed by pjedrzejewski** 2017-08-31 12:51 UTC
Labels: Bug
