### ISSUE TITLE
New Api Product Option Values does not return collection of values

### ISSUE THREAD

**Issue by titi60** [Sylius/Sylius#12138] opened 2020-12-08 18:00 UTC
When calling https://master.demo.sylius.com/new-api/admin/product-options/10662/values on the demo
Api doesn't return option values. The total item count is always 0.

`{
    "@context": "/new-api/contexts/ProductOptionValue",
    "@id": "/new-api/admin/product-options/10662/values",
    "@type": "hydra:Collection",
    "hydra:member": [],
    "hydra:totalItems": 0,
    "hydra:view": {
        "@id": "/new-api/admin/product-options/10662/values?limit=1000",
        "@type": "hydra:PartialCollectionView"
    }
}`

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no/yes
| RFC?             | no/yes
| Sylius version   | 1.8.1

**Comment by Zales0123** [comment] 2020-12-09 08:08
Hi @titi60! As far as I see, the problem is with the description of the `id` field. Even though it's named id (which is the default name in ApiPlatform) we're using **codes** not **IDs** for the entities identification. When using the code it works well:

<img width="819" alt="Zrzut ekranu 2020-12-9 o 09 08 10" src="https://user-images.githubusercontent.com/6212718/101602252-1911b780-39fe-11eb-96d9-83422ea33aca.png">

Can we somehow describe this value in the swagger documentation? cc @lchrusciel @GSadee

**Comment by titi60** [comment] 2020-12-09 08:25
> Hi @titi60! As far as I see, the problem is with the description of the `id` field. Even though it's named id (which is the default name in ApiPlatform) we're using **codes** not **IDs** for the entities identification. When using the code it works well:
> 
> <img alt="Zrzut ekranu 2020-12-9 o 09 08 10" width="819" src="https://user-images.githubusercontent.com/6212718/101602252-1911b780-39fe-11eb-96d9-83422ea33aca.png">
> 
> Can we somehow describe this value in the swagger documentation? cc @lchrusciel @GSadee

Thank you for the reply.

**Comment by NoResponseMate** [comment] 2023-03-16 13:07
Since the parameters' names have been updated to better reflect what is actually needed I'm closing this.

Cheers :beers:

**Closed by NoResponseMate** 2023-03-16 13:07 UTC
Labels: Bug
