### ISSUE TITLE
product image url with full url path

### ISSUE THREAD

**Issue by alexodus** [Sylius/Sylius#8617] opened 2017-09-12 08:29 UTC
Sylius use full path for product image
`
<img src="https://shop.xxxxx.com/media/cache/sylius_shop_product_thumbnail/d6/a5/a5e4a83bd57fb1afe6077ea3aff7.jpeg" alt="SENSORE MOVIMENTO" class="ui bordered image" />
`
I'm using AWS loadbalancer (with associated ssl certificate) with mapping port 443 (for load balancer) to 80 (for 2 http servers). With this setting sylius produce this html:
`
<img src="http://shop.xxxxx.com/media/cache/sylius_shop_product_thumbnail/d6/a5/a5e4a83bd57fb1afe6077ea3aff7.jpeg" alt="SENSORE MOVIMENTO" class="ui bordered image" />
`
and so I cannot see the images.
So, please use full path images (without http(s)://domain/).

**Comment by kochen** [comment] 2017-09-13 08:12
@alexodus Sylius is not setting the domain in the path, it's a combination of LiipImagine bundle (which is responsible for processing and caching the image) and Symfony which I assume is not set to enforce HTTPS like you ELB is.

You should take a look at: http://symfony.com/doc/current/request/load_balancer_reverse_proxy.html
which should solve your issue and allow Symfony to properly set the schema (HTTP/S) on the generated URLs.

**Comment by alexodus** [comment] 2017-09-15 16:05
thanks @kochen, this solve my problem!

**Comment by GSadee** [comment] 2017-09-18 06:28
I'm closing that, because the issue is solved.

**Closed by GSadee** 2017-09-18 06:28 UTC
Labels: Environment
