### ISSUE TITLE
command "server:start" is not defined. 

### ISSUE THREAD

**Issue by samayo** [Sylius/Sylius#10939] opened 2019-12-14 22:18 UTC
**Sylius version affected**: ~1.6.0

**Description**  

Command "server:start" not defined
**Steps to reproduce**  

```
composer create-project sylius/sylius-standard acme
cd acme
php bin/console sylius:install
yarn install
yarn run gulp
php bin/console server:start <- BUG HERE
open http://127.0.0.1:8000
```
**Possible Solution**  

I follow the install documentation from here: https://sylius.com/demo/ and I made sure every requirement was installed and properly configured, but I get this error at the end. 

I think this must be a bug or something lacking from the documentation.

**Comment by Zales0123** [comment] 2019-12-15 09:59
Hello @samayo! Indeed, the information is outdated and we will fix it asap. Right now, the recommended way to run the application in a dev environment is using the [Symfony web server](https://symfony.com/doc/current/setup/symfony_server.html). I hope it helps :)

**Comment by Zales0123** [comment] 2019-12-15 10:00
I'm closing this issue, as it's the duplicate of https://github.com/Sylius/Sylius-Standard/issues/368. Btw, I strongly encourage you to join our [Slack](http://sylius.com/slack) for the quick help with any problems with Sylius ;) 🖖

**Closed by Zales0123** 2019-12-15 10:00 UTC
