### ISSUE TITLE
[Update 1.6.5] Association Missing

### ISSUE THREAD

**Issue by Zortor58** [Sylius/Sylius#11091] opened 2020-02-04 12:52 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Sylius version   | 1.6.5

Since update 1.6.5 I got this error when I try to access Taxon from Back and Front
Class Sylius\\Component\\Core\\Model\\Product has no association named productTaxon

Previous version was 1.6.4
Tried updating database with doctrine with no success (Nothing to update)

**Comment by vvasiloi** [comment] 2020-02-04 12:57
@Zortor58 Can you share a stack trance? Where is the error comming from?

**Comment by Zortor58** [comment] 2020-02-04 13:11
I try to access taxon page from front-end
Same problem on back-end

Route : sylius_shop_product_index
Controller : sylius.controller.product:indexAction

Used to work perfectly, I guess it's related to the DB, bc I have no problems in dev env.

**Comment by vvasiloi** [comment] 2020-02-04 13:13
Did you clear the cache after update?

**Comment by Zortor58** [comment] 2020-02-04 13:19
Cleared cache, executed migrations also and checked database with doctrine

**Comment by vvasiloi** [comment] 2020-02-04 13:27
Well, without a stack trace it's hard to find the issue.
I don't see any changes from 1.6.4 to 1.6.5 that can relate to this issue, maybe you can find something in the log file.
The issued is most likely caused by the combination of this [statement](https://github.com/Sylius/Sylius/blob/a82e52d5916ddb025284355a152becd1ebd30a7e/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php#L52) being skipped and a grid configuration like [this one](https://github.com/Sylius/Sylius/blob/a82e52d5916ddb025284355a152becd1ebd30a7e/src/Sylius/Bundle/ShopBundle/Resources/config/grids/product.yml#L28), or similar scenario.

**Comment by vvasiloi** [comment] 2020-02-04 13:30
Maybe you made some changes to the product repository or the shop/admin product grids before/after the update?

**Comment by Zortor58** [comment] 2020-02-04 14:03
Thank you for ur help, after some research, Sylius 1.6.5 required grid-bundle in 1.6.*, so I downgraded it from 1.7.*. 

After upgrading back to 1.7.* everything was working fine.

**Comment by vvasiloi** [comment] 2020-02-04 14:23
You're welcome!
I guess you can close the issue now.

**Closed** 2020-02-04 14:27 UTC
