### ISSUE TITLE
Problem setting discounts properly

### ISSUE THREAD

**Issue by teratux** [Sylius/Sylius#14896] opened 2023-03-28 03:48 UTC
**Sylius version affected**: 1.11.9

**Description**  
I'm trying to set a discount on a cart for a fixed price, let's say 500.  My idea is to create a cart promotion where I set a rule for a taxon as well as an amount and also set a rule for a max price filter.  If my understanding is correct this should limit the discount applicability to a max cart amount of 500.  When I set it the discounts get applied to everything from 500 up, when it should be only applied to a fixed 500 cart amount.  Is this logic correct? How can I achieve what I want?

![image](https://user-images.githubusercontent.com/92475/228122900-e3e6fdca-c6ad-4cb7-a69d-b3ca31ec145e.png)

**Steps to reproduce**  
Create a cart promotion and set the values showed in the image for a given product

**Comment by teratux** [comment] 2023-04-21 00:56
hello, @TheMilek any thoughts into this?

**Comment by TheMilek** [comment] 2023-04-21 11:55
Hi @teratux!
First of all sorry for the long response ✌🏽 

I have replicated the current cart promotion and from my observation, it appears to be functioning as intended. 

However, I believe there may be an issue with your configuration. It seems that you have set a rule requiring the total price of items from taxon to be at least $500 and also created an item percentage discount with filters that apply a 30% discount for every 'Bajo Demanda' product up to $500, rather than to the order itself. This means that each product has a percentage discount applied individually.

It's possible that you intended to offer discounts for orders in the range of $500 to $500, but unfortunately, this is not feasible as our discounts are offering ranges of order items and not the order itself.
I also think this approach isn't very logical because it's hard for customers to place an order that costs exactly $500.

I suggest maybe using something like that, there is 30% discount for the order that it's total price of items from taxon is above $500:
![image](https://user-images.githubusercontent.com/53942444/233627625-f09f643f-cd32-4ebe-b39b-27c09986047d.png)

I hope I've understood correctly 😅 
Please let me know if my solution helps or if I've missed anything. Also, if there's anything else I can do to assist you 💃🏽 
Cheers! 🍻

**Comment by Rafikooo** [comment] 2023-05-13 12:30
Hello @teratux,

Since we have merged a PR, I will close this ticket. Feel free to ask if you have any more questions 💃 

Best regards,
Rafał

**Closed as completed by Rafikooo** 2023-05-13 12:30 UTC
