### ISSUE TITLE
Add support for Symfony workflow

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#14493] opened 2022-10-31 08:23 UTC
### Catalog promotion

- [ ] State machine configuration

### Order

- [ ] State machine configuration

**Before Placed Order**
- [ ] sylius_assign_number
- [ ] sylius_assign_token

**After Placed Order**
- [ ] sylius_request_shipping
- [ ] sylius_request_payment
- [ ] sylius_create_payment
- [ ] sylius_create_shipment
- [ ] sylius_hold_inventory
- [ ] sylius_increment_promotions_usages
- [ ] sylius_save_addresses_on_customer
- [ ] sylius_set_order_immutable_names

**After Canceled Order**
- [ ] sylius_cancel_payment
- [ ] sylius_cancel_shipment
- [ ] sylius_cancel_order_payment
- [ ] sylius_cancel_order_shipment
- [ ] sylius_cancel_order_inventory
- [ ] sylius_decrement_promotions_usages

### Order checkout

- [ ] State machine configuration

**After Completed Checkout**
- [ ] sylius_create_order
- [ ] sylius_save_checkout_completion_date
- [ ] sylius_control_payment_state
- [ ] sylius_control_shipping_state

**After Selected Shipping**
- [ ] sylius_process_cart
- [ ] sylius_skip_payment

**After Addressed**
- [ ] sylius_process_cart

**After Selected Payment**
- [ ] sylius_process_cart

**After Skipped Shipping**
- [ ] sylius_process_cart

#### After Skipped Payment
- [ ] sylius_process_cart

### Order payment

- [ ] State machine configuration

**After Paid**
- [ ] sylius_order_paid
- [ ] sylius_resolve_state

### Order shipping

- [ ] State machine configuration

**After Shipped**
- [ ] sylius_resolve_state

### Payment

- [ ] State machine configuration

**After Failed Payment**
- [ ] sylius_process_order

**After Canceled Payment**
- [ ] sylius_process_order

**After Completed Payment**
- [ ] sylius_resolve_state

**After Processed Payment**
- [ ] sylius_resolve_state

**After Refunded Payment**
- [ ] sylius_resolve_state

**After Authorized Payment**
- [ ] sylius_resolve_state

### Product Review

- [ ] State machine configuration

**After Accepted Product Review**
- [ ] sylius_update_rating

### Shipment

- [ ] State machine configuration

**Before Shipped**
- [ ] sylius_assign_date

**After Shipped**
- [ ] sylius_resolve_state

**Comment by jakubtobiasz** [comment] 2022-11-04 14:18
Hi @loic425!
Is it a duplicate of #14495? If yes - can we close it?

**Comment by lchrusciel** [comment] 2022-12-07 19:21
Closing in favour of https://github.com/Sylius/Sylius/issues/14495

**Closed as completed by lchrusciel** 2022-12-07 19:21 UTC

**Comment by loic425** [comment] 2022-12-07 21:19
Oh yes indeed, this is strange @jakubtobiasz
