### ISSUE TITLE
Create order at backend

### ISSUE THREAD

**Issue by mingxing** [Sylius/Sylius#3770] opened 2015-12-23 01:30 UTC
Hi guys

Could we create backend order now? It display "Not implemented yet.".

Thank you
Simon

**Comment by pjedrzejewski** [comment] 2015-12-23 08:22
Duplicate of https://github.com/Sylius/Sylius/issues/3688.

**Comment by pjedrzejewski** [comment] 2015-12-23 08:22
@mingxing Please continue discussion in the issue I linked above. :) Thanks!

**Closed by pjedrzejewski** 2015-12-23 08:22 UTC

**Comment by synerskills** [comment] 2016-01-02 06:40
Thank you a lot!
