### ISSUE TITLE
Product association : ajax product search fails

### ISSUE THREAD

**Issue by edouardT** [Sylius/Sylius#9364] opened 2018-04-24 18:05 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1

With more than 100 products in database and long text contents, espacially in description field (including html), when you modify a product in back-office and want to make a new product association, if you search a product in the dropdown selector, the request is really slow or fails.

The first thing is that the response returns all fields of the product in the JSON Response while we only need the name and the code of the product. So, it takes a lot of time to serialize the whole object and after, it takes a lot of time to display the list in the javascript function.

I didn't find if it's possible to request a part of the product field and not the whole object.

That's problematic because in a lot of case the request take too much time and stops, so we can't select any product for the association...

**Comment by stefandoorn** [comment] 2018-06-03 09:42
More information in duplicate ticket #9411.

**Comment by stefandoorn** [comment] 2018-08-28 09:03
I can confirm this issue also occurs on `1.2.x`.

**Comment by GusTTShowbiz** [comment] 2018-09-13 13:47
Hi, 
It appears issue https://github.com/Sylius/Sylius/issues/9411 points to https://github.com/Sylius/Sylius/issues/9364, and https://github.com/Sylius/Sylius/issues/9364 points to https://github.com/Sylius/Sylius/issues/9411. Both are closed, so I don't know if anyone's working on a fix or has already found a solution?
Thanks

**Comment by pamil** [comment] 2018-10-03 14:27
Should be fixed by #9775.

**Comment by andychan94** [comment] 2018-12-25 04:49
@Zales0123 Has this really been fixed? Because my project still fails to load the list of products. I am using symfony 4.2 with sylius 1.3. Sorry for disturbing but I really cannot find a solution to this problem

**Comment by edouardT** [comment] 2018-12-26 18:37
@Zales0123 @andychan94 I confirm this bug is not fixed. Like I said, the problem is in the json response which returns all product data instead of product name. I don't know if it's easy to change it... Let me know if you find a solution. I will try to fix this in the next few weeks if I can.

**Comment by andychan94** [comment] 2019-01-17 05:44
@edouardT sorry, any progress yet? If you are busy maybe I could try to work on it if you can give me details? Thanks!

**Comment by andychan94** [comment] 2019-01-17 09:33
Correct. Would appreciate if anyone shares a solution they found for this

**Comment by Takeno** [comment] 2019-01-17 10:03
My workaround was replace the route with a custom action.

routes.yaml
```
sylius_admin_ajax_product_index:
    path: /admin/ajax/products/
    methods: [GET]
    defaults:
        _controller: AppBundle:Admin\Custom:searchProduct
        _format: json
```

CustomController.php
```
    public function searchProductAction(Request $request) {
        $repo = $this->get('sylius.repository.product');

        $criteria = $request->query->get('criteria');
        $q = $criteria['search']['value'];

        $items = $repo->findBySearch($q);

        return new JsonResponse([
            '_embedded' => [
                'items' => $items,
            ]
        ]);
    }
```

`findBySearch` is a simple query in `ProductRepository.php` which returns just id, name and code. You should be able to get the json's schema from a fresh installation.

**Comment by stefandoorn** [comment] 2019-01-21 11:20
@Zales0123 @pamil What about adding the suggestion above into core?

**Comment by andychan94** [comment] 2019-02-03 07:31
@Takeno could you please show ur custom method in `ProductRepository.php`? I followed the sylius docs to customize repositories, but I cannot figure out how to return just id, name and code. Thanks in advance!

**Comment by Takeno** [comment] 2019-02-03 12:20
@andychan94 something like this:
```php
    public function findBySearch($term)
    {
        return $this->createQueryBuilder('o')
            ->select('translation.name')
            ->addSelect('o.code')
            ->innerJoin('o.translations', 'translation', 'WITH', 'translation.locale = :locale')
            ->addOrderBy('o.updatedAt', 'DESC')
            ->andWhere('o.code LIKE :term')
            ->orWhere('translation.name LIKE :term')
            ->setParameter('locale', 'it_IT')
            ->setParameter('term', '%' . $term . '%')
            ->setMaxResults(20)
            ->getQuery()
            ->getResult();
    }
```

**Comment by jcgdjob** [comment] 2019-02-04 03:15
> If I do not extend the `ResourceController`, then I obviously get
> 
> > {
> > "code": 500,
> > "message": "Notice: Undefined property: App\Controller\CustomController::$container"
> > }
> 

Try `extends AbstractController` instead.

`use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;`

**Comment by andychan94** [comment] 2019-02-04 08:33
@jcgdjob thank you! Seems like this is working fine! Thank you guys so much!

**Comment by Prometee** [comment] 2019-07-17 18:41
This bug occurred also for me (Sylius 1.5.2, Sf 4.3.2) and surprisingly it stop when I add the `serialization_groups` into the route :

```
sylius_admin_ajax_product_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _format: json
        _sylius:
            permission: true
            grid: sylius_admin_product
            serialization_groups: [Default]
```

I also try with `Autocomplete` but it wasn't working giving back an empty json object (`{}`) but only `Default` is working.

Xdebugging it without the `serialization_groups` it appears to loop infinitely into the JMS serialization process.

**Comment by olia-bn** [comment] 2020-01-21 11:17
I agree, this should be re-opened!
It is still present in 1.6.4

GraphNavigator is timing out:
`Maximum execution time of x seconds exceeded in /vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php on line 331, referer: /admin/products/{id}/edit`

**Comment by Prometee** [comment] 2020-01-21 13:06
@olia-bn you are right to fix the bug you have to put an override with the correct path into `config/routes/sylius_admin.yaml` for exemple.

**Comment by TELLO0815** [comment] 2020-05-03 15:41
Hi all, I tried the solution: 
`sylius_admin_ajax_product_index:
    path: /admin/ajax/products/
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _format: json
        _sylius:
            permission: true
            grid: sylius_admin_product
            serialization_groups: [Default]`

But for me its not working. (Not in 1.6 and also not in 1.7.3

Any ideas?

**Comment by Prometee** [comment] 2020-05-04 09:29
@TELLO0815 rechecking my fix proposition on 1.7.3 and it's working, do you debug the route definition in console : `./bin/console debug:route sylius_admin_ajax_product_index`

**Comment by TELLO0815** [comment] 2020-05-04 10:40
@Prometee  
```
| Route Name   | sylius_admin_ajax_product_index                                                                                           |
| Path         | /                                                                                                                         |
| Path Regex   | #^/$#sD                                                                                                                   |
| Host         | ANY                                                                                                                       |
| Host Regex   |                                                                                                                           |
| Scheme       | ANY                                                                                                                       |
| Method       | GET                                                                                                                       |
| Requirements | NO CUSTOM                                                                                                                 |
| Class        | Symfony\Component\Routing\Route                                                                                           |
| Defaults     | _controller: sylius.controller.product:indexAction                                                                        |
|              | _format: json                                                                                                             |
|              | _sylius: array ('permission' => true,'grid' => 'sylius_admin_product','serialization_groups' => array (0 => 'Default',),) |
| Options      | compiler_class: Symfony\Component\Routing\RouteCompiler 
```

**Comment by Prometee** [comment] 2020-05-04 12:44
@TELLO0815 I don't have the same `Path Regexp` and `Path` I got :
```
| Route Name   | sylius_admin_ajax_product_index                                                                                           |
| Path         | /admin/ajax/products                                                                                                      |
| Path Regex   | #^/admin/ajax/products$#sD                                                                                                |
| Host         | ANY                                                                                                                       |
| Host Regex   |                                                                                                                           |
| Scheme       | ANY                                                                                                                       |
| Method       | GET                                                                                                                       |
| Requirements | NO CUSTOM                                                                                                                 |
| Class        | Symfony\Component\Routing\Route                                                                                           |
| Defaults     | _controller: sylius.controller.product:indexAction                                                                        |
|              | _format: json                                                                                                             |
|              | _sylius: array ('serialization_groups' => array (0 => 'Default',),'permission' => true,'grid' => 'sylius_admin_product',) |
| Options      | compiler_class: Symfony\Component\Routing\RouteCompiler                                                                   |
```

**Comment by Prometee** [comment] 2020-05-04 12:57
Here is my full override :

```
# config/routes/sylius_admin.yaml

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

# Bug infinite loop into admin product associations selection
# https://github.com/Sylius/Sylius/issues/9364
sylius_admin_ajax_product_index:
    path: /admin/ajax/products
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _format: json
        _sylius:
            serialization_groups: [Default]
            permission: true
            grid: sylius_admin_product

```

**Comment by TELLO0815** [comment] 2020-05-04 15:46
Works. THX

**Comment by lchrusciel** [comment] 2020-05-05 11:37
Hey folks, it seems like it is something we could fix in the core. Would you like to open a PR with the fix? Preferably with some PHPUnit test (if you will be able to make this call there, as it would be a first one). 

You can find some inspirations for tests here: https://github.com/Sylius/Sylius/blob/master/tests/Controller/AdminUserApiTest.php

**Comment by Prometee** [comment] 2020-05-05 12:40
@lchrusciel I'm on it, I see that there is a fixture with an admin user now I have to found how to authenticate it in the unit test.

**Comment by lchrusciel** [comment] 2020-05-05 12:44
if you are using nelmio fixtures, just add following array:
https://github.com/Sylius/Sylius/blob/0e9d41dd7b4146e9330b229b91f417a85c72ceb0/tests/Controller/AdminUserApiTest.php#L23-L26

Also, there are fixtures with a product already as well

**Comment by Prometee** [comment] 2020-05-05 12:47
I see, authenticate with the bearer will work even if it's an `/admin/ajax` route, I'll test it. Thanks @lchrusciel !

**Closed** 2020-05-12 19:48 UTC
Labels: Bug

**Comment by starmate** [comment] 2020-09-01 08:49
Hi @Prometee,

I just found this thread and as I am facing similar issue, I though maybe you could give some insights.

When I try to add associated products (v1.7.6), I am not able to see the drop down list. There is no ajax requets (verified with developer tool). Seems to me that it is js issue, but I don't have any error message.

When I manually load url from data-url attribut, I get a json list, which seems to work, but when I am on the input text for associated product selection, nothing happens.

Do you know what may cause this?

Thanks in advance

**Comment by Prometee** [comment] 2020-09-01 20:41
@starmate I suspect something related with javascript setup at first sight, maybe you can ask for more help on Sylius's Slack support channel.

**Comment by starmate** [comment] 2020-09-02 03:56
Hi @Prometee ,

Yes it was actually. It was generated by glitch with mollie module in their app.js (v3.2.3).

Seems to be fixed from v2.3.4.

**Comment by bellu** [comment] 2021-11-17 10:07
I'm using Sylius 1.10 and the problem is still here.
The only solution that works is the @Takeno one.

**Comment by mickael-naturopera** [comment] 2022-05-13 13:21
> My workaround was replace the route with a custom action.
> 
> routes.yaml
> 
> ```
> sylius_admin_ajax_product_index:
>     path: /admin/ajax/products/
>     methods: [GET]
>     defaults:
>         _controller: AppBundle:Admin\Custom:searchProduct
>         _format: json
> ```
> 
> CustomController.php
> 
> ```
>     public function searchProductAction(Request $request) {
>         $repo = $this->get('sylius.repository.product');
> 
>         $criteria = $request->query->get('criteria');
>         $q = $criteria['search']['value'];
> 
>         $items = $repo->findBySearch($q);
> 
>         return new JsonResponse([
>             '_embedded' => [
>                 'items' => $items,
>             ]
>         ]);
>     }
> ```
> 
> `findBySearch` is a simple query in `ProductRepository.php` which returns just id, name and code. You should be able to get the json's schema from a fresh installation.

thank you very mutch you are the best

**Comment by seizan8** [comment] 2023-06-09 14:28
Sylius 1.10.14, still running into this issue. I either get an out of memory or max execution time reached error. Or the response simply contains no data. I tried to debug it for like 2 hours but it's not really that simple.
My best guess would be that the JMS serializer gets trapped in an endless loop when it actually finds a product. 

Overwritting the route with a custom action is very simple and works easily. So thanks once more to @Takeno for this work around.

**Comment by carlosromero** [comment] 2024-06-06 17:42
I think the error is related with new attributes added to Product entity that the Default serilization is not able to serialize properly, in my case it was solved replacing  in the route declaration `serialization_groups:[Default]`  by `serialization_groups: {0: Default, items: [Autocomplete]}`

Add to the final of config/routes/sylius_admin.yaml:
```
sylius_admin_ajax_product_index:
    path: /admin/ajax/products/
    methods: [GET]
    defaults:
        _controller: sylius.controller.product::indexAction
        _format: json
        _sylius:
            serialization_groups: {0: Default, items: [Autocomplete]}
            permission: true
            grid: sylius_admin_product
```

**Comment by oliver-schulz** [comment] 2024-06-25 08:15
Woah, i have exactly the same "not working" admin route. the fix form @carlosromero works perfectly. And he fixed a Bug :)

The error i was getting:
`{"code":500,"message":"No locale has been set and current locale is undefined."}`. 

Thx for sharing your finding @carlosromero !!
