### ISSUE TITLE
[Possible BUG] How to handle taxon updates when you support 2 locales

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#4107] opened 2016-02-10 15:54 UTC
Let's say we want following taxonomy structure for a Sylius instance:

Structure for EN locale:
- Root
  - Perfumes
  - Accessories
    - Watches
  - Make-up

The same structure for PL locale with the following translations:
- Korzeń
  - Perfumy
  - Akcesoria
    - Zegarki
  - Makijaż

Let's say we import the data through a userland import bundle implementation.

The problem is the current data is not 100% accurate and sometimes there are typos or missing PL translations. To ensure the import does not fail and we get to update the errors in the Sylius interface, we have a "strict mode" we keep off for the import, so we end up with this kind of categories for EN:
- Root
  - Perfumes
  - Acesories
    - Watches
  - Make-up

And this kind of tranlsations for PL:
- Korzeń
  - Perfumy
  - Akcesoria
    - Watches
  - Makijaż

After import, a data entry operator goes to admin an renames "Acesories" with "Accessories" and "Watches" with "Zegarki".

At this point, the permalink of watches becomes `/root/accessories/watches`, but for translation it's still `/korzen/akcesoria/watches` although it should be `/korzen/akcesoria/zegarki`

Any ideas how to tackle this?

Sylius version: 0.16.

**Comment by michalmarcinkowski** [comment] 2016-11-18 20:30
Now you can use `sylius.generator.taxon_slug` service to regenerate the slug after name update 😉  Closing as it's not a bug, if you need more information let me know.

**Closed by michalmarcinkowski** 2016-11-18 20:30 UTC
Labels: Bug
