### ISSUE TITLE
Sylius 1.11.11 API - can't create new taxox

### ISSUE THREAD

**Issue by LeoMoshko** [Sylius/Sylius#14666] opened 2022-12-22 19:48 UTC
**Sylius version affected** -  1.11.11

**Description**  
It is not possible to create a new taxon from API-Platform. I get the error as in the attachment

**Steps to reproduce**  
1. Go to http://your-domain/api/v2/docs
2. Get JWT token using endpoint "POST /api/v2/admin/authentication-token"
3. Authenticate with swagger
4. Run endpoint "POST /api/v2/admin/taxons" with standard body 
5. 
<img width="1324" alt="Zrzut ekranu 2022-12-22 o 22 13 25" src="https://user-images.githubusercontent.com/9072581/209215715-bdeb054f-0f34-4ac9-b138-7fc939d63c12.png">

**Comment by TheMilek** [comment] 2023-01-05 14:49
Hi @LeoMoshko!
Thank you for reporting the issue, I reproduced the problem on Sylius 1.11, 1.12 seems to be working fine💃🏽 
We will try to take care of it and come with some solution 🚀

**Comment by jakubtobiasz** [comment] 2023-02-10 11:40
Closing as 1.11 is not supported anymore, and it works on Sylius 1.12 and above. Thanks for reporting!

**Closed as completed by jakubtobiasz** 2023-02-10 11:40 UTC
Labels: API, Bug
