### ISSUE TITLE
Taxonomy Issues

### ISSUE THREAD

**Issue by Richtermeister** [Sylius/Sylius#478] opened 2013-10-29 06:10 UTC
Hi all,

I noticed a few issues/areas for improvement for the Taxonomy Bundle.

 * When removing taxons, sometimes siblings get removed (not just children). This looks like a gedmo mapping issue.. Does the gedmo:tree-root parameter need to be mapped?

 * The parent/children properties are mapped in the CoreBundle, but it should be possible to keep this mapping in the TaxonomiesBundle (against Interfaces). Is this just a remnant from the pre-DRTE days?

 * There is a Taxonomy.orm.xml mapping file in the CoreBundle that adds nothing to the mapping other than the table name. Is this neccessary, or can the table name live in the Taxonomies bundle? It seems where the table name lives is inconsistent from bundle to bundle..

I'm happy to tackle these issues if I could get some feedback on these questions.

Thanks!

**Comment by pjedrzejewski** [comment] 2015-02-24 13:09
@beleneglorion Why would you delete root taxon? Root taxon has all other taxons under it, so it removes them as well.

**Comment by beleneglorion** [comment] 2015-02-25 18:31
@pjedrzejewski i think you misunderstood the problem,
 Root Taxon A
    -> Child A1
    -> Child A2
     .
    -> Child An
    Root Taxon B
    -> Child B1
    -> Child B2
     .
    -> Child Bn

When you delete Root A taxon () Taxon child taxons from Root B are deleted to ....

and i need to delete a root Taxon because some time my client remove a category from his catalogue of tools ;)

**Comment by antipodes1010** [comment] 2015-03-30 21:19
Any updates on this one?

I have the same issue like the first point.
To reproduce:

Taxon 1
--> child 1.1

Taxon 2
--> child 2.1

Delete Taxon 1 and then neither Taxon 1 and 2 would show up.
Check the sylius_taxon table, all four would have 'deleted_at' values.

And change 'cascade-all' to 'cascade-persist' does not work for me, complaint about 'slug' cannot be null.

**Comment by michalmarcinkowski** [comment] 2016-01-29 09:47
Will be fixed in #3773.

**Comment by michalmarcinkowski** [comment] 2016-03-20 22:59
Should be fixed already

**Closed by michalmarcinkowski** 2016-03-20 22:59 UTC
Labels: Bug, Feature Request
