### ISSUE TITLE
switch translation in checkout flow automatically when go back to previous step

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#5336] opened 2016-06-23 14:12 UTC
When a customer starts to checkout his order, he has filled data for  addressing, shipping steps , then he go back to addressing step , and try to correct his address,  press `Next` again,  Sylius will complain 

>Transition address cannot be applied on state shipping_selected of object Sylius\Component\Core\Model\Order with graph sylius_order_checkout

I know the checkout state of this order has changed to shipping_selected， if we want the customer can readdress his address, we need to  apply translation `readdress`. I  think this should happen automatically in the checkout flow, it will happen a lot  that a customer wants to go back to previous step, what do you think?

**Comment by Zales0123** [comment] 2016-06-23 14:23
@videni we're still working on new shop checkout implementation. It's not finished yet and we are focusing on making checkout work in the most basic case (simple step-by-step passing by). It's also very important for behat scenarios to make checkout fully passable.
When it's done, we'll be implementing features you're talking about. There is still many things to consider (e.g. when ``re...`` transitions should be applied, as running them on ``GET`` on each step is filthy) but you can be sure its one of the biggest priorities to make it work as soon as possible :)
However, thanks for reporting, good to be open-eyed 🏇  😄

**Comment by Niiko** [comment] 2016-06-23 15:08
Duplicate of #5264 maybe ?

**Comment by videni** [comment] 2016-07-20 09:42
@Zales0123 , what is the latest progress of this feature, can you share your idea ? maybe I can  speed it up a bit. right now , this is major obstacle stopping us putting our system online.

**Comment by michalmarcinkowski** [comment] 2016-09-15 07:08
Already fixed in #5956 and #5945.

**Closed by michalmarcinkowski** 2016-09-15 07:08 UTC
