### ISSUE TITLE
Error duplicate taxonomy

### ISSUE THREAD

**Issue by felcorrea** [Sylius/Sylius#3570] opened 2015-11-14 13:58 UTC
Hi,

I'm new in Sylius and during the tests I found a possible error, as follows. I'm using Sylius Standard 0.15.0-dev.

When I try create a new taxonomy with an existing Name and Location I receive the error (this is in my localhost):

Link: http://localhost/sylius_standard/web/app_dev.php/administration/taxonomies/new
Message:

> An exception occurred while executing 'INSERT INTO sylius_taxon_translation (name, slug, permalink, description, locale, translatable_id) VALUES (?, ?, ?, ?, ?, ?)' with params ["Categorias", "categorias", "categorias", null, "pt_BR", 35]:
> 
> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pt_BR-categorias' for key 'permalink_uidx'

In http://demo.sylius.org/administration/taxonomies/new when I try create a new taxonomy with Location "En_us" and Name "CATEGORY" the error 500 Internal Server Error appears, because this name already exists in this location.

In \vendor\sylius\sylius\src\Sylius\Bundle\TaxonomyBundle\Resources\config\validation.xml there's a constraint for unique locale and permalink with a message, but I don't know why this message isn't used:

```
    .....
    <class name="Sylius\Component\Taxonomy\Model\TaxonTranslation">
        .....
        <constraint name="Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity">
            <option name="fields">
            <value>locale</value>
            <value>permalink</value>
            </option>
            <option name="message">sylius.permalink.unique</option>
            <option name="groups">sylius</option>
        </constraint>
    </class>
```

**Comment by steffenbrem** [comment] 2016-01-06 15:58
@felcorrea It is because the permalink is generated by doctrine `prePersist` event. So the validator won't have it I guess. I am having the same issue, but I am afraid you cannot validate fields that use the gedmo slug extension.

**Comment by jeroendesloovere** [comment] 2016-09-19 07:48
Duplicate for #3661?

**Comment by pix-art** [comment] 2016-10-17 08:23
This issue seems fixed with the new admin/code, since it's been here for really long. 

<img width="1352" alt="screenshot 2016-10-17 10 22 43" src="https://cloud.githubusercontent.com/assets/1973973/19430213/aefe5b72-9453-11e6-97de-119029ead3e9.png">

**Comment by pjedrzejewski** [comment] 2016-10-17 11:33
@pix-art Thanks!

**Comment by michalmarcinkowski** [comment] 2016-10-28 15:44
The issue is not fixed, try to add taxon with the same name without specifying permalink.

**Closed** 2016-11-18 08:12 UTC
Labels: Bug
