### ISSUE TITLE
Still getting "&locale=..." parameter after disabling localised URLs

### ISSUE THREAD

**Issue by davidromani** [Sylius/Sylius#8217] opened 2017-06-29 15:37 UTC
Hello

One question... after following this recipe http://docs.sylius.org/en/latest/cookbook/disabling-localised-urls.html, I'm still getting a dirty path ("&locale=...") only in taxon & product details routes.

What can I check to fix it?

Thx.

**Comment by venyii** [comment] 2017-06-29 15:59
Duplicate of #7970

**Closed** 2017-06-29 16:19 UTC
