### ISSUE TITLE
 Error: File not found with singular glob:

### ISSUE THREAD

**Issue by maiskiykot** [Sylius/Sylius#17470] opened 2024-11-14 17:07 UTC
yarn build  have error^

* Error: File not found with singular glob: /var/www/*/data/www/*/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/gulpfile.babel.js (if this was purposeful, use `allowEmpty` option)

 I check directory AdminBundle - it not content gulpfile.babel.js. What I can do?

**Comment by kulczy** [comment] 2024-11-15 09:56
hi @maiskiykot . Could you please provide more details so we can reproduce this error? For example, which version are you using, and when did the error start occurring (e.g., after an update)?

**Comment by GSadee** [comment] 2024-12-05 13:58
I'm closing due to lack of replies and additional information. If you have any further problems, please use the Slack community or open a new ticket.

**Closed as completed by GSadee** 2024-12-05 13:58 UTC
Labels: Potential Bug, Frontend
