### ISSUE TITLE
Two promotions, where one invalidates the other, makes checkout impossible

### ISSUE THREAD

**Issue by alexrowesoap** [Sylius/Sylius#9940] opened 2018-11-20 15:32 UTC
**Sylius version affected**: 1.2.10

**Description**  
If you have two promotions that both apply for a cart, but when both apply, checkout becomes impossible if one changes the order value as such to invalidate the other.

**Steps to reproduce**  

1. Create a Christmas promotion (this is a demo one)
- no usage limit
- Priority 0
- no date restriction
- configuration
- - One rule
- - - Cart Quantity = 0
- - One action
- - - Order Percentage discount = 26
2. Create a New Years promotion (this is also a demo one)
- usage limit = 10
- priority 2
- dates to cover the testing period
- configuration
- - One rule
- - - item total = $100
- - One action
- - - order fixed discount = 10
3. Go to the front-end
4. Add 1 $100 item to the basket (20% tax item)
5. Proceed through the checkout to the complete page, and confirm both promotions have applied bringing the total down to $79.92 (free shipping)
6. Click place order
7. You should see an error of "Error. You are no longer eligible for this promotion New Year."

**Possible Solution**  
Not a clue at the moment

**Comment by Zales0123** [comment] 2018-11-26 08:08
Thank you, Alex, for the report, we will take a deeper look at it in the nearest future (hopefully) and come up with some solution ideas :)

**Comment by Zales0123** [comment] 2018-11-26 14:43
Do you think you could provide a Behat scenario describing this bug? BTW, I suppose `Cart Quantity = 0` is not a valid configuration of the promotion rule (unless it's a typo :))

**Comment by alexrowesoap** [comment] 2018-11-26 15:11
Hey @Zales0123 I'll see if I can get one together. I think the fixture that generates the test data picks a random integer, but seemingly 0 is valid if set manually.

**Comment by Zales0123** [comment] 2018-11-26 15:23
Well, then it should not be for sure, minimum cart quantity should always be `1` :)

**Comment by alexrowesoap** [comment] 2018-11-26 15:36
two bugs in one! :joy: 
I've never written a behat scenario before, but here goes!

	Feature: Ensure promotions work correctly
		In order to checkout successfully with promotions
		As a Visitor
		I want to checkout successfully with promotions

		Background:
			Given the store operates on a single channel in "United States"
			And default tax zone is "US"
			And the store has included in price "US VAT" tax rate of 23% for "Clothes" within the "US" zone
			And the store has a product "PHP T-Shirt" priced at "$100.00"
			And it belongs to "Clothes" tax category
			And there is a promotion "Christmas"
			And the promotion gives "12%" off
			And there is a promotion "New Year"
			And the promotion gives "$10.00" off if item total is greater than "$100.00"
			And the store ships everywhere for free
			And the store allows paying offline

		@ui
		Scenario: Basket with several promotions is able to checkout
			Given I have product "PHP T-Shirt" in the cart
			And I have completed addressing step with email "john@example.com" and "United States" based shipping address
			And I have proceeded order with "Free" shipping method and "Offline" payment
        		When I confirm my order
        		Then an email with the summary of order placed by "john@example.com" should be sent to him`

**Comment by tautelis** [comment] 2019-02-12 09:32
I encountered the same bug on 1.3.* with default fixtures.

After taking a deeper look I found out where the problem hides:
in `PromotionProcessor` and `OrderPromotionIntegrityChecker` promotions are applied in different order. Therefore while applying promotion in `PromotionProcessor` the new_year promotion is applied first and conditions fit. At checkout the `OrderPromotionIntegrityChecker` applies christmas promotion first which decreased order total so that the new_year promotion is no longer eligible.

To reproduce the bug make sure that christmas promotion drops order total below 100$.

![screen shot 2019-02-12 at 11 31 24](https://user-images.githubusercontent.com/6945396/52625492-ccb8c780-2eb9-11e9-9c31-0ee61a0e63fb.png)

**Comment by alexrowesoap** [comment] 2019-05-13 11:01
Please do not stale

**Comment by tautelis** [comment] 2019-05-30 08:02
Any progress on this important bug? There are moments when it is impossible to checkout due to this.

**Comment by loevgaard** [comment] 2019-06-04 11:07
Hi @tautelis 

It looks like you created something that looked like a solution. Could you create a PR to demonstrate that it works and create tests for it?

**Comment by pamil** [comment] 2019-08-22 08:35
Should be fixed by #10603.

**Closed by pamil** 2019-08-22 08:35 UTC
Labels: Potential Bug
