### ISSUE TITLE
[ResourceBundle][RFC] Request attributes and parameters parsing

### ISSUE THREAD

**Issue by cdaguerre** [Sylius/Sylius#2850] opened 2015-06-12 13:48 UTC
IMO, it's quite confusing where request parameters are parsed right now.
Some of the magic happens in: 
- the `KernelControllerSubscriber`
- the `ParametersParser`
- the `Configuration`

I'm not sure as to where this all should take place, but I think it should be moved to a single place.
I'd be glad to help out on this ;)

**Comment by aRn0D** [comment] 2015-06-17 07:22
The parameters are parsed by the `ParametersParser`, this class is used in `KernelControllerSubscriber` to parse request parameters and `Configuration` to parse language expression. Perhaps the problem is that the`ParametersParser` does not respect the single responsibility principle.

**Comment by cdaguerre** [comment] 2015-06-17 08:32
I agree with the fact that the `ParametersParser` has two responsibilities.
- Parsing language expression
- Parsing request parameters

As to parsing request parameters:
- This happens exclusively in the `KernelControllerSubscriber` (not in the `Configuration`)

As to parsing language expression:
- RIght now, this happens in `Configuration` (ie. [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/Configuration.php#L248)) and this is actually the **only** place the `ParametersParser` is used in the `Configuration`

So, to my understanding, right now the only reason we inject the `ParametersParser` into the `Configuration` is to parse language expressions in redirect parameters (ie. its second responsibility, not its main one).
Since this is the only place requiring language expression parsing right now, I'd say we could move this to the `RedirectHandler` and remove the dependency of the `Configuration` and `ConfigurationFactory` on the `ParametersParser`.

Hence my PR #2849

**Comment by pjedrzejewski** [comment] 2015-08-13 09:57
Fixed in #2255.

**Closed by pjedrzejewski** 2015-08-13 09:57 UTC
