### ISSUE TITLE
Product Builder with custom Variant model not working

### ISSUE THREAD

**Issue by mirague** [Sylius/Sylius#1207] opened 2014-03-14 13:39 UTC
Heya, I've been staring myself blind on this issue where I cannot seem to get the `Product Builder` working when trying to implement my own version of `Variant`. I'm getting the following error:
```
Found entity of type Sylius\Bundle\CoreBundle\Model\Variant on association 
Shopfish\Bundle\CoreBundle\Entity\Product#variants, but expecting 
Shopfish\Bundle\CoreBundle\Entity\Variant
```

I've overridden my class from the models found in `CoreBundle`, updated the `sylius.yml` configs to point to my own classes and yet it does not work.

On Stackoverflow I've posted about this with full code-snippets, but realized this might be a bug since I've done everything correct as far as I'm concerned. Please see for yourself, I'm happy to hear if I've done something incorrectly:
http://stackoverflow.com/questions/22402614/sylius-product-builder-not-using-expected-entity-override

Thanks!

**Comment by michalmarcinkowski** [comment] 2015-12-14 13:42
Duplicate of https://github.com/Sylius/Sylius/issues/480. Should be fixed soon.

**Closed by michalmarcinkowski** 2015-12-14 13:42 UTC
Labels: Support Request
