### ISSUE TITLE
[Proposal] New Backend Theme in Sylius and more...

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3014] opened 2015-07-15 14:51 UTC
Hye everyone :)

I'm migrating all Backend Responsive Theme with Boostrap 3.3 with more Translations(FR)/Components/UI/Chartrs/Widgets/Macros/Helpers..

Should it look like this:

![capture du 2015-07-15 16 47 47](https://cloud.githubusercontent.com/assets/1421325/8701362/99c02850-2b11-11e5-8e93-97d6365667be.png)
![capture du 2015-07-15 16 48 46](https://cloud.githubusercontent.com/assets/1421325/8701361/99bec21c-2b11-11e5-9abd-036534362846.png)
![Uploading Capture du 2015-07-15 16:49:03.png…]()
![capture du 2015-07-15 16 49 30](https://cloud.githubusercontent.com/assets/1421325/8701364/99c24446-2b11-11e5-892b-88a12dc7a305.png)

**Comment by pamil** [comment] 2015-07-16 07:11
Yes, it looks great!

**Comment by gperdomor** [comment] 2015-07-19 23:24
This is not an issue so i think must be closed or at least change the title and prepend [Proposal] or something like that :)

**Comment by elliot** [comment] 2015-07-20 00:39
Does the license for [PixelAdmin ](https://wrapbootstrap.com/theme/pixeladmin-premium-admin-theme-WB07403R9) cover distribution in an open source application?

**Comment by Symfomany** [comment] 2015-07-20 10:39
:+1: @gperdomor  Ok!

**Comment by kayue** [comment] 2015-07-20 11:52
@Symfomany Before you start you probably want to collaborate with @pjedrzejewski first, he might have something working in progress already.

**Comment by teriu** [comment] 2015-08-01 04:51
Is this a duplicate of #3041 ?

**Comment by pjedrzejewski** [comment] 2015-08-13 09:51
Duplicate of #3041, see my comment there.

**Closed by pjedrzejewski** 2015-08-13 09:51 UTC
