### ISSUE TITLE
mutil chanel on backend, the frontend error

### ISSUE THREAD

**Issue by benyang2015** [Sylius/Sylius#8792] opened 2017-10-07 13:10 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

Uncaught PHP Exception Sylius\Component\Channel\Context\ChannelNotFoundException: "Channel could not be found! Tip: You can use the Web Debug Toolbar to switch between channels in development.

**Comment by Koc** [comment] 2017-10-07 13:17
Possible duplicate of #981

**Comment by gabiudrescu** [comment] 2017-10-08 11:07
have you followed the installation instructions correctly?

**Comment by benyang2015** [comment] 2017-10-08 12:43
yes, followed the installation
$ composer create-project sylius/sylius-standard my-sylius-shop && cd my-sylius-shop
$ php bin/console sylius:install
$ yarn install && yarn run gulp
$ php bin/console server:start

**Comment by gabiudrescu** [comment] 2017-10-08 18:26
have you opted for using dummy data? or have you played around with Channels configuration?

**Comment by benyang2015** [comment] 2017-10-09 04:59
how to config channel？where the doc

**Comment by GSadee** [comment] 2017-10-09 07:04
@benyang2015 please use issues to report bugs, propose new features or discuss new functionalities. However, when you are creating an issue, describe it as good as you can.

**Comment by lchrusciel** [comment] 2017-10-23 06:51
Probably misconfiguration of channels. Closing.

**Closed by lchrusciel** 2017-10-23 06:51 UTC
