### ISSUE TITLE
Some missing and wrong information in "How to migrate from Gulp to Webpack"

### ISSUE THREAD

**Issue by elboletaire** [Sylius/Sylius#14401] opened 2022-10-03 13:12 UTC
**Sylius docs version**: 1.12 / latest

**Description**
- In [How to migrate from Gulp to Webpack](https://docs.sylius.com/en/latest/cookbook/frontend/migrating-to-webpack.html), despiste the great improvement in the section, there's no indication about installing the webpack encore package:

~~~bash
composer require symfony/webpack-encore-bundle
~~~

- The section where it says to remove some packages, one of them is `gulpfile.js`, but I think that one should be `gulpfile.babel.js` instead.

- I also faced another issue following this documentation that I do not have following the 1.11 version. From a 1.11.8 installation, following the documentation, when running yarn build (aka yarn encore dev) an error appears when trying to build the assets, the exact same error as described in #12560. It fails finding a `chart.js` dependency file:

![imatge](https://user-images.githubusercontent.com/153305/193583601-d997f01b-9716-4854-a48e-bc3d73bfa937.png)

If I instead follow [the old 1.11 documentation](https://docs.sylius.com/en/1.11/cookbook/frontend/webpack.html), I do not have any problem with this chart.js dependency (and the chart is properly shown in the admin, whilst with the other procedure there's no chart at all). The main changes between both procedures are the `package.json` and `webpack.config.js`, in the 1.11 documentation you were using the already given files, while in the new documentation you're copying the latest tagged github versions.

I tried creating a project from the 1.12.x-dev branch but obviously there's no problem at all, since webpack encore is already replacing gulp and there's no action needed.

Update: ~~If I only copy the `package.json` file (without touching the webpack one) the build fails with a missing `moment` dependency, but it can be fixed by manually adding it (`yarn add moment`), and then the build works without issues. So I guess there's something different between how files are loaded between versions in webpack.~~ Nevermind... the Chart.js problem is due to sylius version. Latest version properly point to `chart.min.js` instead of `Chart.min.js`.

More updates: This documentation shows to modify the scripts and styles files with a line prefixed with `app`. Doing so makes some of the JS of the shop and admin to start doing weird things, like there are multiple scripts overlapped. Moreover, removing these additional `app` prefixed lines fixes this weird issue.

**Comment by jakubtobiasz** [comment] 2022-10-19 16:42
Hi @elboletaire!
Thanks for your feedback! I hope #14461 will do the work :). Feel free to participate in reviewing!

**Comment by elboletaire** [comment] 2022-10-19 19:40
Are the `app` prefixed manifest imports required? They were bugging both my front and my admin, making most actions unresponsive (or glitchy, like I had to click multiple times because there were scripts duplicated).

**Comment by jakubtobiasz** [comment] 2022-10-19 19:47
@elboletaire, we use them to separate Sylius' admin and shop part from the app's one to allow override of every possible thing. Can you tell me in which places the bug occurs, your OS, web browser, and other useful stuff which can help me debug it?

**Comment by elboletaire** [comment] 2022-10-19 19:52
AFAIR, I was using sylius 1.11. An example of issues I was having: in the taxons menu, trying to open the context menu to edit a taxon, wouldn't properly show it. Instead, it would show and hide immediately.

My OS is Windows and my browser is Firefox; the dev host/server is an Arch linux tho.

Maybe I should try again with a fresh install, but I can't recall changing anything related to styles other than when switching to webpack-encore and, as I described before, the experimented issue was like I was adding the exact same scripts twice, and it actually was fixed when I removed the `app` prefixed ones.

**Comment by jakubtobiasz** [comment] 2022-10-19 21:47
It might be caused by `.` between `app` and `shop`. I will replace it with an underscore, and it should do the work.

**Comment by jakubtobiasz** [comment] 2022-11-03 09:13
As the main problem is solved, I am closing this issue. I could not reproduce your second issue, and the new structure does not seem to affect this. Try to clear the browser cache, reinstall dependencies, check on other devices and open a new issue if needed 🖖🏻.

**Closed as completed by jakubtobiasz** 2022-11-03 09:13 UTC
Labels: Documentation, Frontend
