### ISSUE TITLE
Doctrine metadata cache bug related to Product & Sluggable

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#1363] opened 2014-04-12 03:26 UTC
Hi all

In our site, sluggable in `Product` is malfunctioning when doctrine metadata cache is on (I was testing with APC). This cause `null` product slug when creating new product.

I have posted an issue in Doctrine: https://github.com/doctrine/common/issues/320

Kindly let me know if you know a work around for this problem, I think this might be related to how we extend product class.

**Comment by michalmarcinkowski** [comment] 2015-10-02 13:26
Is it fixed on master?

**Comment by pjedrzejewski** [comment] 2015-10-07 08:12
@michalmarcinkowski Don't think so.

**Comment by inssein** [comment] 2015-11-04 03:05
So is no one using APC with Sylius? This issue went away for a little bit earlier, not sure how, but its now back again for me.

**Comment by pestaa** [comment] 2015-11-11 09:37
We're using Redis cache for Doctrine metadata, and indeed this bug is alive.

Although I had to move ProductTranslation's slug field definition to the core bundle. (The Product entity seems fine.)

**Comment by pestaa** [comment] 2015-11-12 08:22
I came closer to the truth. In `\Gedmo\Mapping\ExtensionMetadataFactory::getExtensionMetadata()` it's trying to find slug fields for core models, but those are defined in separate components, for which models metadata is not yet loaded (i.e. when looking for slug fields in `\Sylius\Component\Core\Model\ProductTranslation` it tries to scan `\Sylius\Component\Product\Model\ProductTranslation`).

I still do not know why superclass mappings are delayed so much so that SluggableListener (and others?) can come first.

I'm implementing a workaround using a preFlush event listener to load all (or only those relevant) metadata classes.

**Comment by inssein** [comment] 2015-11-12 16:44
@pestaa I was looking at that earlier, but I'm not sure that is the answer. I don't know Doctrine well enough to know why the metadata works without caching.

**Comment by pestaa** [comment] 2015-11-13 13:29
We're not sure either, but the native `getMetadataFor` seems to load only the child class' metadata if it is available in the cache (i.e. by not calling `loadMetadata` it avoids unrolling the class hierarchy).

**Closed** 2015-11-19 15:53 UTC
Labels: Bug

**Comment by inssein** [comment] 2015-11-25 03:44
@pjedrzejewski The issue specifically related to the generation of slugs is fixed because of the  ProductTranslationSlugEventListener, the APC caching bug still exists. I can't pinpoint exact details yet, but the last 4 orders created in my application have the "updated_at" set to null, but "created_at" worked fine.

**Comment by pamil** [comment] 2015-11-25 23:01
@kayue @Richtermeister @pestaa can you check whether the issue is still present after #3627?
