### ISSUE TITLE
Overriding Attribute

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#2294] opened 2015-01-01 16:43 UTC
In `sylius.yml` config:

```
sylius_attribute:
    classes:
        product:
            subject: %sylius.model.product.class%
            attribute:
                form: Umpirsky\Bundle\CoreBundle\Form\Type\AttributeType
                model: Umpirsky\Bundle\CoreBundle\Entity\Attribute
            attribute_value:
                form: Umpirsky\Bundle\CoreBundle\Form\Type\ProductAttributeValueType
```

I get error when trying to load fixtures:
```
 [Doctrine\DBAL\DBALException]                                                                                                        
  An exception occurred while executing 'INSERT INTO sylius_product_attribute_translation (presentation, locale, translatable_id) VAL  
  UES (?, ?, ?)' with params ["Brand", "en", null]:                                                                                    
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'translatable_id' cannot be null 
```

Am I missing something?

/cc @gonzalovilaseca

**Comment by steffenbrem** [comment] 2015-01-01 16:48
Hey, this is related to this issue: #2268

**Comment by umpirsky** [comment] 2015-01-01 17:32
@steffenbrem Oh, this is a deal breaker. Thanks for letting me know, I would like to at least be able to disable translation for Attribute.

I tried to override:

```php
protected function getTranslationEntityClass()
{
    return get_parent_class($this).'Translation';
}
```
in my `Attribute` model. But still getting same error, I think this is not related with override issue.

**Comment by steffenbrem** [comment] 2015-01-01 20:55
@umpirsky What I did, was forking Sylius and replaced the doctrine mapping files with my own Translation models. That way, it will work. When Sylius fixes it, I simply switch back to the original repository without weird code changes.

**Comment by inspiran** [comment] 2015-01-01 21:02
@umpirsky FYI, it happens to all models, not just Attribute.

**Comment by umpirsky** [comment] 2015-01-02 11:15
No, for me it happens only with `Attribute`.

@inspiran Do you also get ` SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'translatable_id' cannot be null`?

**Comment by umpirsky** [comment] 2015-01-02 12:54
Ah, yes, you are right, it is related with issue: #2268. :(

**Comment by inspiran** [comment] 2015-01-02 13:11
@umpirsky yep.   I had to revert to 0.12 .

**Comment by umpirsky** [comment] 2015-01-14 12:26
@gonzalovilaseca Nope, I am still getting same error. Can you give me some hints how to debug it? Thanks.

**Comment by gonzalovilaseca** [comment] 2015-01-14 12:35
@umpirsky Do ```Umpirsky\Bundle\CoreBundle\Entity\Attribute``` or ```Umpirskyt\Bundle\CoreBundle\Entity\AttributeTranslation``` have a doctrine mapping? Can you post it?

**Comment by inspiran** [comment] 2015-01-14 12:37
@gonzalovilaseca  Fixed here, thx.

**Comment by umpirsky** [comment] 2015-01-14 12:59
@gonzalovilaseca Here it is:

```php
<?php

use Sylius\Component\Product\Model\Attribute as BaseAttribute;

/**
 * @ORM\Entity
 * @ORM\Table(name="sylius_product_attribute")
 */
class Attribute extends BaseAttribute
{
    public function __toString()
    {
        return $this->name;
    }

    protected function getTranslationEntityClass()
    {
        return get_parent_class($this).'Translation';
    }
}
```

As you can see, I use translation class from parent bundle: `Sylius\Component\Product\Model\AttributeTranslation`.

**Comment by gonzalovilaseca** [comment] 2015-01-14 13:34
@umpirsky I meant the doctrine mapping.

**Comment by umpirsky** [comment] 2015-01-14 13:35
@gonzalovilaseca I use annotations, so that's it.

```
/**
 * @ORM\Entity
 * @ORM\Table(name="sylius_product_attribute")
 */
```

**Comment by gonzalovilaseca** [comment] 2015-01-14 13:39
Ok, I see.
First problem I see is that translations don't support annotations mapping (only xml and yml).
Another problem I see is that ```protected function getTranslationEntityClass()
    {
        return get_parent_class($this).'Translation';
    }``` is returning the parent translation class, but in config the translation is defined as ```attribute_translation:
                model: Umpirskyt\Bundle\CoreBundle\Entity\AttributeTranslation```

**Comment by umpirsky** [comment] 2015-01-14 14:00
@gonzalovilaseca Oh, too bad, I already have a plenty of extended models with annotations mapping. Any workarounds? Any plans to support that?

Regarding config, just forgot to update issue description, I do not configure `attribute_translation: model:`.

Thanks.

**Comment by umpirsky** [comment] 2015-01-14 14:21
@pjedrzejewski So, you are practically forcing people to use xml or yml mapping if they want to override translatable models? If this is true, that is quite limiting.

**Comment by gonzalovilaseca** [comment] 2015-01-14 14:29
@umpirsky Is there a chance I can clone your repo to have a deeper look into the issue?

**Comment by umpirsky** [comment] 2015-01-14 14:57
@gonzalovilaseca Yes, I prepared the simplest example for you. You can see it on https://github.com/umpirsky/Sylius/tree/fix/issue-2294.

Here is what is the diff with master https://github.com/umpirsky/Sylius/commit/73a075c4182c3165675cfc0c20f1817976452493.

Thanks for looking into it, I really appreciate it!

**Comment by gonzalovilaseca** [comment] 2015-01-14 15:00
@umpirsky NP. Will let you know as soon as I find something.

**Comment by umpirsky** [comment] 2015-01-14 15:03
@gonzalovilaseca Great, thanks!

**Comment by pjedrzejewski** [comment] 2015-01-14 20:15
@umpirsky @gonzalovilaseca  Adding Annotations driver for translations would fix the issue? Damn, I wanted to release v0.13.0.

**Comment by gonzalovilaseca** [comment] 2015-01-14 20:22
@pjedrzejewski Not sure about it. Will let you know as soon as I find something.

**Comment by inspiran** [comment] 2015-01-17 13:43
@gonzalovilaseca 

Seems  I  am having issues while loading the sylius Taxonomy fixtures.   Do I need to configure something in order to get translations working ?

Fatal error: Call to a member function get() on null in .../vendor/sylius/sylius/src/Sylius/Component/Translation/Model/AbstractTranslatable.php on line 196

**Comment by gonzalovilaseca** [comment] 2015-01-19 09:23
@inspiran Yes, it's the same proble @umpirsky is having. I had a look but haven't found the issue yet. Will try to find some time this week to solve it.

**Comment by gonzalovilaseca** [comment] 2015-01-22 09:25
@inspiran @umpirsky The problem is that the mapped manytoOne relation between the translation entity and the translatable entity is not using the custom entity but the Sylius one.
Will update as soon as I find a clean solution.

**Comment by gonzalovilaseca** [comment] 2015-01-22 09:34
@umpirsky Try this temporary mapping, it will work:
```
<?xml version="1.0" encoding="UTF-8" ?>

<!--

 This file is part of the Sylius package.

 (c) Paweł Jędrzejewski

 For the full copyright and license information, please view the LICENSE
 file that was distributed with this source code.

-->

<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:prezent="prezent">

    <mapped-superclass name="Sylius\Component\Product\Model\AttributeTranslation" table="sylius_product_attribute_translation">
        <prezent:translatable target-entity="Sylius\Bundle\UmpirskyBundle\Entity\Attribute" />
    </mapped-superclass>
    
</doctrine-mapping>
```
I'm working on a final solution.

**Comment by gonzalovilaseca** [comment] 2015-01-22 10:04
@pjedrzejewski I'm thinking that moving away from Prezent is going to be the best solution. Instead of having the mapping in the xml/yml files, I would move it to Sylius configuration, so that overriding values would be quite straight forward.

**Comment by inspiran** [comment] 2015-01-22 10:08
+1 For that.   From the moment you override a model (eg. sylius_product.classes.model) the prezent configuration should be adjusted.  Compiler pass?

**Comment by gonzalovilaseca** [comment] 2015-01-22 10:15
Yes, the more I think about it, the more I like the idea. 
Overall it will be more simple, and I'm also thinking that I'm also going to add the possibility of defining custom translatable entities via configuration, in the same way one can define custom attributes for classes or a sylius resource.
Will update as soon as I have something.

**Comment by adamelso** [comment] 2015-01-22 20:39
Hi @gonzalovilaseca This might be of interest. I've having this error with Doctrine using both the implement and the Sylius class for the where clause when it should only be using one. Do 

```
 An exception has been thrown during the rendering of a template ("An exception occurred while executing 

'SELECT
  Acme_Bundle_AdvertisementBundle_Model_AttributeTranslation.presentation AS presentation0,
  Acme_Bundle_AdvertisementBundle_Model_AttributeTranslation.id AS id1,
  Acme_Bundle_AdvertisementBundle_Model_AttributeTranslation.locale AS locale2,
  Acme_Bundle_AdvertisementBundle_Model_AttributeTranslation.translatable_id AS translatable_id3 FROM
  acme_advertisement_attribute_translation Acme_Bundle_AdvertisementBundle_Model_AttributeTranslation
WHERE
  Acme_Bundle_AdvertisementBundle_Model_AttributeTranslation.translatable_id = ?
AND
  Sylius_Component_Attribute_Model_AttributeTranslation.locale = ?
LIMIT 1' with params [1, "en"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Sylius_Component_Attribute_Model_AttributeTranslation.locale' in 'where clause'") in AcmeAdvertisementBundle:Advertisement:show.html.twig at line 82. 
```

**Comment by gonzalovilaseca** [comment] 2015-01-22 21:23
@adamelso I'm refactoring the whole bundle, this will probably (and hopefully :-))be solved with the new version.

**Comment by adamelso** [comment] 2015-01-22 23:24
@gonzalovilaseca  Excellent! However, my bad actually because I forget the ProductBundle automatically configures the attributes, when for my app I needed to explicitly configure `sylius_attribute.attribute_value`. I don't get the error after that. I would update the docs, but as you're refactoring the bundle, I'll wait until then. :)

**Comment by antonioperic** [comment] 2015-01-23 08:11
I also tried to override some product in the way that worked before, but have similar problem

  [Doctrine\ORM\Mapping\MappingException]                                                                    
  The target-entity Locastic\Bundle\CoreBundle\Entity\Product cannot be found in 'Sylius\Component\Product\  
  Model\AttributeValue#subject'.                                                                             
                                  

sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: Locastic\Bundle\CoreBundle\Entity\Product
            controller: Sylius\Bundle\CoreBundle\Controller\ProductController
            repository: Sylius\Bundle\CoreBundle\Doctrine\ORM\ProductRepository
            form:
                default: Sylius\Bundle\CoreBundle\Form\Type\ProductType

**Comment by inspiran** [comment] 2015-01-23 14:50
@gonzalovilaseca  FYI, seems the product form in admin also has an issue.    I am getting an error :  Class "Application\SiteBundle\Entity\ProductTranslation" not found. Is the "data_class" form option set correctly?     Note that i did not override the ProductTranslation class, only the Product class.

**Comment by gonzalovilaseca** [comment] 2015-01-23 17:40
Just finished the refactoring (PR #2377).

Now the mapping is defined in config.yml.
So for @umprisky it would be:
```
sylius_attribute:
    classes:
        product:
            subject: %sylius.model.product.class%
            attribute:
                form: Umpirsky\Bundle\CoreBundle\Form\Type\AttributeType
                model: Umpirsky\Bundle\CoreBundle\Entity\Attribute
                translatable:
                     targetEntity: Sylius\Component\Product\Model\AttributeTranslation
            attribute_translation:
                translation:
                    targetEntity: Umpirsky\Bundle\CoreBundle\Entity\Attribute
            attribute_value:
                form: Umpirsky\Bundle\CoreBundle\Form\Type\ProductAttributeValueType

```
Doctrine maps a one to many association bidirectionally, so both directions have to be remapped/redefined ... hope this makes sense.

**Comment by gonzalovilaseca** [comment] 2015-01-29 11:36
@umpirsky @steffenbrem @inspiran @antonioperic The refactoring has been merged.
Just make sure that the ``getTranslationEntityClass()`` method in translatable entity returns the translation class defined in configuration.
Let me know if you have any problems.

**Comment by umpirsky** [comment] 2015-01-29 13:11
@gonzalovilaseca Thanks. Will get back to you when I have time to test it out. Thanks!

**Comment by aRn0D** [comment] 2015-04-22 11:19
@umpirsky fixed ?

**Comment by umpirsky** [comment] 2015-04-22 11:51
@aRn0D I think it is.

**Comment by aRn0D** [comment] 2015-04-22 11:54
ok I close it !

**Closed by aRn0D** 2015-04-22 11:54 UTC
Labels: Awaiting Feedback
