### ISSUE TITLE
Monthly statistics with an extra day

### ISSUE THREAD

**Issue by antiseptikk** [Sylius/Sylius#14281] opened 2022-09-07 10:28 UTC
**Sylius version affected**: 1.8+ ?

**Description**  
I noted that the monthly statistics were calculated over a period including the 1st day of the following month.

I think this is confusing for sellers because they all asked me to change the behavior. 

**Steps to reproduce**  
Just navigate between month **with sales** in first day of following month

<img width="1464" alt="image" src="https://user-images.githubusercontent.com/1520152/188856006-1d6c079d-3cb1-4799-a69e-13beea3bf203.png">

**Possible Solution**  
Decrease the end date by one second to have endDate like : 31/08/2022 23:59:59

**Comment by Rafikooo** [comment] 2022-10-05 08:44
Hi Thomas, I've checked your submission and unfortunately cannot reproduce it. I've tried both locally and on our demos and it looks to be working fine. You can try to do this [here](https://master.demo.sylius.com/admin/) by yourself.
I wonder if you have introduced any custom configuration into your app that affects this component?

**Comment by CoderMaggie** [comment] 2022-10-14 08:02
It's been a few days and we did not get a response from you. As we did not manage to reproduce it I'm closing the issue. Please reopen if needed 🖖🏻

**Closed as completed by CoderMaggie** 2022-10-14 08:02 UTC
Labels: Help Wanted, Admin
