### ISSUE TITLE
Could not load type "sylius_product_option_value_collection"

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#6260] opened 2016-10-02 00:14 UTC
I am trying to edit a variant in the admin, but I get the error in the title (Could not load type "sylius_product_option_value_collection").

From some quick debugging, it seems like it is looking for OptionValueCollectionType, but it was deleted in https://github.com/Sylius/Sylius/pull/6150/commits/ae22e0e700c29d2f91bf244cdb59f19d6b6658f3.

@pamil should I revert it, or did you mean to do something else?

**Comment by gdecorbiac** [comment] 2016-10-03 08:26
@pamil @inssein 
this is the same bug as [#6230](https://github.com/Sylius/Sylius/issues/6230) and [#6150](https://github.com/Sylius/Sylius/pull/6150)

**Comment by pjedrzejewski** [comment] 2016-10-03 08:30
Duplicate of #6230.

**Closed** 2016-10-03 08:30 UTC
