### ISSUE TITLE
Issue with currency and locale 

### ISSUE THREAD

**Issue by yosriMekni** [Sylius/Sylius#6586] opened 2016-10-28 13:32 UTC
i've added some currencies and locales in the admin panel but when i dump locales and currencies varibles in the "_locale.html.twig" and "_currency.html.twig" its only shows one element wich is the first one in the sylius_currency and sylius_locale tables , knowing that i've make sure that their are aperfectly added

**Comment by michalmarcinkowski** [comment] 2016-10-28 13:34
Duplicate of #6585

**Closed by michalmarcinkowski** 2016-10-28 13:34 UTC
