### ISSUE TITLE
LocaleBundle Header based locale sniffing breaks two letter locales

### ISSUE THREAD

**Issue by guycalledseven** [Sylius/Sylius#14868] opened 2023-03-21 02:31 UTC
**Sylius version affected**: 1.12.0-1.12.5

**Description**  

On a site that has 2 languages configured via 2 letter locales, after upgrading Sylius to 1.12. only english locale works.

**Steps to reproduce**  

Create default installation. Add two languages using ISO 639-1 in locale (eg. 'en' for English and 'hr' for Croatian)
When switched to other language than 'en', locale remains 'en'.

If locales are entered as ISO 15897 (eg. `en_EN` English United States  and `hr_HR` Croatian Croatia  - locale / localisation / language switcher works as expected. 

**Possible Solution**  

The issue lies in this commit in LocaleBundle that adds Header based locale sniffing.
https://github.com/Sylius/SyliusLocaleBundle/commit/9464905f4cfc89131baafa62f4d7f3861abe87a7#diff-5dc7d7dcf78698e0d0cf5b1113d5c44c036a217a689f35f3d336bacae13d06abR42

```
        <service id="Sylius\Bundle\LocaleBundle\Context\RequestHeaderBasedLocaleContext">
            <argument type="service" id="request_stack" />
            <argument type="service" id="sylius.locale_provider" />
            <tag name="sylius.context.locale" priority="256" />
        </service>
```

This overrides language set in url and in turns breaks localisation on that language.

This should be configurable at best, if not removed from defaults at all.

Bug is related to this pull request - https://github.com/Sylius/Sylius/pull/13708

**Comment by jakubtobiasz** [comment] 2023-03-21 09:25
Hi @guycalledseven 🙋🏼‍♂️!
The locale context you mentioned is probably not causing the issue you experience. If finding a locale basing on the request header fails, it goes to the request-based searching. I guess there's a problem with Channel/Locale settings in the Admin Panel. Can you send us your locale/channel settings accordingly to these examples:

1) `/admin/locales`
![CleanShot 2023-03-21 at 10 24 13](https://user-images.githubusercontent.com/80641364/226564486-748c103f-eef2-42f0-8237-19a8835dbf4d.png)

2) `/admin/channels/<your_channel_id/edit`
![CleanShot 2023-03-21 at 10 24 40](https://user-images.githubusercontent.com/80641364/226564607-7b241d0f-a91f-4b7f-9a5e-490207decda9.png)

**Comment by guycalledseven** [comment] 2023-03-21 09:38
Yes, here it is - just 'en' and 'hr', and 'hr' is default. This configuration worked in all last known Sylius versions (from 1.0 probably).

![image](https://user-images.githubusercontent.com/1009843/226566124-d318b532-723a-4aa6-a22b-ee81f7d827fd.png)

I am aware that `RequestLocaleSetter` set's wrong locale to $request and breaks things

```
    public function onKernelRequest(RequestEvent $event): void
    {
        $request = $event->getRequest();

        $request->setLocale($this->localeContext->getLocaleCode());
        $request->setDefaultLocale($this->localeProvider->getDefaultLocaleCode());
    }
```

and when `CompositeLocaleContext` calls `getLocaleCode` in foreach loop it goes over queue of items and if found returns wrong locale (does not process other ones) in `CompositeLocaleContext`:

```
        foreach ($this->localeContexts as $localeContext) {
            try {
                return $localeContext->getLocaleCode(); // ovo vrati 'en' a trebao bi hr
            } catch (LocaleNotFoundException $exception) {
                $lastException = $exception;

                continue;
            }
        }
```

if i disable service by force or by overriding it in services.yml 2 letter locales work again:

```
services:

    Sylius\Bundle\LocaleBundle\Context\RequestHeaderBasedLocaleContext:
        alias: null    
```

**Comment by jakubtobiasz** [comment] 2023-03-27 05:41
Hello @guycalledseven 🙋🏼‍♂️!
Are you sure this isn't working on Sylius 1.12.5? I tried to reproduce this bug on both development branch of Sylius 1.12 and Sylius Standard 1.12.5 and it seems to be working correctly. I'm attaching a video to let you check whether I missed something.

https://user-images.githubusercontent.com/80641364/227850524-8651ba70-c597-4d98-bb5a-b3af0c469f49.mp4

**Comment by guycalledseven** [comment] 2023-03-30 12:09
@jakubtobiasz I've tested latest 1.12.x-dev version and two letter locales are working as they should 👍
I've installed with "hr", then added "en" in locales, and assigned both to test channel. and it works correctly without need to change priorities.

**Comment by jakubtobiasz** [comment] 2023-03-30 12:56
@guycalledseven may you check on `1.12.6`, please? We released it 2 days ago, so it should work. In such case, I guess we can close this issue, as only `1.12.x` versions were affected (at least from what you said) :).

**Comment by guycalledseven** [comment] 2023-03-30 14:22
@jakubtobiasz I checked now actual released version and it works ok. 
I even run diff against 1.12.x and 1.12.6 to see differences, vendor folder was the same (sylius/sylius with 1.12.6 verison pulled)

my first test was installed via

```
composer create-project sylius/sylius-standard:1.12.x-dev .
```

second test via 

```
composer create-project sylius/sylius-standard .
```

in 1.12.x I have some annotations added to entities etc. I am guessing that those are new changes from sylius/sylius-standard package. but overall - 2 letter lang codes work.

however, when I tried to upgrade my local project to 1.12.6 - I still need to disable this in services.yaml in order for two letter lang codes to work.

```    
services:
    Sylius\Bundle\LocaleBundle\Context\RequestHeaderBasedLocaleContext:
        alias: null    
```

 I will double check config folders, especially locales for default installation and mine.

I am afraid that reasons for such behaviour are not even in config, but database.... will report back.

**Comment by guycalledseven** [comment] 2023-03-31 23:21
@jakubtobiasz ok, so I retested everything because  at one point I started getting strange behaviour (eg. latest dev again not working). So, what I found out was that my tests done in chrome incognito vs. chrome non-incognito gave very different results. Chrome Incognito was one causing the issue to appear because as it seems incognito Chrome sends `Accept-Language: en` header, which in turn causes strange behaviour to appear. 

I did default installation again from dev-master and 1.12.6. Added 2 locales to the channel like in your video (en, pl). 
Language switcher was working just fine in Chrome, but in Chrome Incognito language was defaulted to 'en'.
You can test it locally with curl. 

This defaults language to english no matter `pl` is in url.

```
curl 'http://127.0.0.1:8000/pl/' \
  -H 'Accept-Language: en' \
  | grep -i zaloguj
```

This will work correctly (there is no Accept-Language:header) :

```
  curl 'http://127.0.0.1:8000/pl/' \
    | grep -i zaloguj
```

I don't think that should happen. For me the visible locale in url has some sort of priority in language selection.

Also, this does not happen if eg:
- 4 letter locales are used or
- if one of locales is eg en-US, and other pl.

**Comment by jakubtobiasz** [comment] 2023-05-02 10:05
Thanks for debugging this @guycalledseven!
I managed to reproduce it, and I'm creating a task for it in our internal issue tracking system :).

**Closed as completed** 2023-05-25 11:26 UTC
Labels: Bug
