### ISSUE TITLE
Shipping method choice form has no promotion displayed

### ISSUE THREAD

**Issue by Tomsgu** [Sylius/Sylius#12629] opened 2021-05-12 13:22 UTC
**Sylius version affected**: 1.8, 1.9

**Description**  
If you have a promotion with an action "shipping percentage discount" and you're on the checkout shipping page. On the right side (Estimated shipping cost) discount is applied correctly, but on the select shipping form, choices are displayed without any discount.

![shipping_promotion_display](https://user-images.githubusercontent.com/2694769/117979151-e6fcdc80-b332-11eb-9ede-e36297f5e20f.png)

**Steps to reproduce**  
1. Create a promotion with action "shipping percentage discount" and any rule.
2. Place products to a cart in a way that discount rule will be applied.
3. Make a checkout - fill an address and on following page you will see the inconsistencies displayed on the image on top.

**Possible Solution**  
Somehow calculate the discount here:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodChoiceType.php#L103 Not really clear to me how to apply a discount without having an order object with selected shipping method.

**Comment by CoderMaggie** [comment] 2022-07-12 12:21
hiiiii @Tomsgu!

Even though it is possible to change that, as the Sylius Product Owner I must say that the ratio of effort to value is for me too low. We would have to process the whole Order to be able to display the discounted shipping price and we should do that for every shipping method. We will not be able to deliver that feature anytime soon, that's why I'm closing this issue.

Furthermore, it is a duplicate of #9748

**Closed by CoderMaggie** 2022-07-12 12:21 UTC
Labels: Feature
