### ISSUE TITLE
Case sensitivity on postgres causes existing customers not to be recognized at checkout.

### ISSUE THREAD

**Issue by tdestro** [Sylius/Sylius#14252] opened 2022-08-22 22:37 UTC
**Sylius version affected**: 1.11.0

**Description**  

https://github.com/Sylius/Sylius/blob/30884eb1df74a2e6a48544936d0a4495f3c8785d/src/Sylius/Bundle/CoreBundle/Form/Type/Customer/CustomerGuestType.php#L50

The behavior of this line of code differs depending on what database you are using. 

    Mysql makes case insensitive queries
    Postgres makes case sensitive queries

Under postgres, if an existing customer is in the sylius_customer table with the email address Test@sylius.com and that customer later attempts to go through checkout again, typing test@sylius.com into the email address field on the form at checkout/address, this code will fail to identify the existing customer because on postgres it is case sensitive. 

**Steps to reproduce**  
- Deploy sylius on postgres.
- Go through the checkout process, use Test@sylius.com as the customer email address.
- Go through the checkout process, use test@sylius.com as the customer email address.

Line of code above will fail to recognize that the customer exists and a constraint violation will occur when it attempts to insert the customer into the sylius_customer table a second time.

**Possible Solution**  
Canonicalize the inputted email address in CustomerGuestType and compare against email_canonical instead of the email column.

or maybe

Ensure that when schema is created it is somehow made case insensitive at the database level(?)

I would also note that this issue is systemic and that there may be other places where the program makes the assumption that the resulting query is case insensitive.

**Comment by Zales0123** [comment] 2022-09-05 08:23
Hello Tony! Thank you for the bug report. Indeed we should probably canonicalize the email in this listener. Maybe you could propose a PR with a bug fix? That would be great! Thanks in advance 🚀 🖖

**Comment by dennisgon** [comment] 2022-10-01 17:23
Hi can propose a PR for this bug?

**Comment by markbeazley** [comment] 2022-10-10 11:25
I think this is a duplicate of #13201 which has a potential fix in this PR #13202

**Comment by GSadee** [comment] 2022-11-07 07:46
I'm closing the issue as it should be fixed by https://github.com/Sylius/Sylius/pull/13202

**Closed as completed by GSadee** 2022-11-07 07:46 UTC
Labels: Bug
