### ISSUE TITLE
[Feature Request] Shop Product Import 

### ISSUE THREAD

**Issue by doertedev** [Sylius/Sylius#1290] opened 2014-03-26 16:48 UTC
OHAI.

One of our clients whants a webshop which can programmagically import products, images, prices, descriptions etc from his existing Ebay and Amazon store.

See: https://twitter.com/pjedrzejewski/status/448861242917408768

**Comment by michalmarcinkowski** [comment] 2015-12-14 13:33
Duplicate of https://github.com/Sylius/Sylius/issues/2242

**Closed by michalmarcinkowski** 2015-12-14 13:33 UTC
Labels: Feature Request, Future

**Comment by lsmith77** [comment] 2017-11-07 12:16
still a work in progress but hopefully soon this will be full featured: https://github.com/FriendsOfSylius/SyliusImportExportPlugin
