### ISSUE TITLE
[UI] Text going out of the frame in product description

### ISSUE THREAD

**Issue by marekrzytki** [Sylius/Sylius#16068] opened 2024-03-28 10:06 UTC
**Sylius version affected**: 1.12.13

**Description**  
Too long product description lines going off the frame
Can be reproduced on current demo
![2024-03-28_10-58](https://github.com/Sylius/Sylius/assets/61479357/4fe670f6-40c4-4294-8c63-02244e095512)

**Steps to reproduce**  

1. Edit any product in admin panel
2. Fill description field with long lines text
3. Save
4. Check product page

**Possible Solution**  
Possibly text wrap in description twig template

**Comment by crydotsnake** [comment] 2024-03-30 13:15
As an alternative you could also add spaces when you have a long description. Also i could not reproduce this as the text breaks automatically in to a new line in the backend when editing the description.

**Comment by crydotsnake** [comment] 2024-03-30 13:56
I could reproduce it.

As in #16076 i would suggest to introduce a new CSS Class/ID and apply the `word-break: break-word;` there.

Because if i would add it to one of those classes: `ui bottom attached tab segment active` i'm not sure, if it could break something at any other place.

Wdyt @Rafikooo, @Wojdylak ?

**Comment by Wojdylak** [comment] 2024-04-08 10:53
I am closing this issue as it has been resolved by PR #16099

**Closed as completed by Wojdylak** 2024-04-08 10:53 UTC
