### ISSUE TITLE
Issue with unique indexes on email and emailCanonical on sylius_customer table

### ISSUE THREAD

**Issue by awerffeli** [Sylius/Sylius#4055] opened 2016-02-04 13:29 UTC
When deleting a customer in the sylius backend it is not actually deleted but the deleted_at field is set. so when deleting a customer and this same customer with the same email wants to register again this is not possible due to the unique index. This also leads to migration failing when upgrading to 0.16 as there may already be multiple entries with the same email when the migration tries to add the unique index.

https://github.com/Sylius/Sylius/commit/76f8974f1c721e83f9ba5b2070c2f6fe1b602822

**Comment by pamil** [comment] 2016-02-04 13:31
Deleted at will be removed on User and Customer by #4009.

**Comment by michalmarcinkowski** [comment] 2016-02-04 21:29
Duplicate of #2537.

**Closed by michalmarcinkowski** 2016-02-04 21:29 UTC
Labels: Bug
