### ISSUE TITLE
Unable to retrieve Product translations

### ISSUE THREAD

**Issue by bellu** [Sylius/Sylius#13341] opened 2021-11-29 18:24 UTC
**Sylius version affected**: 1.10.5

**Description**  
I'm trying to retrieve all the translations available for a product.
But using `$product->getTranslation('en')` return the translations only for the currentLocale.

ps: i've this product available in two languages with the codes: 'it' and 'en'.

**Comment by mynameisbogdan** [comment] 2021-12-06 14:01
How about `$product->getTranslations()`? 

It's defined in `Sylius\Component\Resource\Model\TranslatableInterface`.

**Comment by bellu** [comment] 2021-12-06 14:16
I have already tried, `$product->getTranslations()` returns an array of translations with only the current locale.

**Comment by mynameisbogdan** [comment] 2021-12-06 14:27
That happened to me when there's a `->andWhere('translation.locale = :locale')` or `->innerJoin('o.translations', 'translation', 'WITH', 'translation.locale = :locale')` in query builder.

Can you check if there's a restriction by locale for the translation in the repository method you're using to fetch the products?

**Comment by Zales0123** [comment] 2022-01-04 12:06
Hello @bellu? Have you managed to figure out what is going on? Maybe the tip from @mynameisbogdan worked for you? Please, give us an update :)

**Comment by NoResponseMate** [comment] 2023-03-28 10:09
Hi @bellu

I'm closing it since we cannot reproduce this issue.
If you'd want to provide more context ping me and I'll reopen it.

Cheers :beers:

**Closed by NoResponseMate** 2023-03-28 10:09 UTC
Labels: Potential Bug

**Comment by SuperToma** [comment] 2023-08-18 19:34
Hello @NoResponseMate  :raising_hand_man:
I have the same issue, here is a sample code:
```
$product = $this->productRepository->findOneByChannelAndSlug(
    $channel, $this->localeContext->getLocaleCode(), $currentSlug
);

dump($product); // the collection in the 'translation' property contains only 1 element instead of 2
```

It looks that's caused by the innerJoin/WITH but if somebody has a tip it would be great.

Thanks !

**Comment by bellu** [comment] 2024-04-18 08:25
I updated to 1.10.9 but the bug seems to be still here. Any news?

**Comment by NoResponseMate** [comment] 2024-04-18 14:09
Hi @bellu :wave:
The thing is, this isn't a bug, it's pretty much a customization problem.

By default, we're limiting the translations taken from the DB to only a specific locale since getting all of them can be pretty resource-heavy.

Basically, to achieve what you want, you'll first need to locate which repository method is responsible for getting the product/s and either overwrite or better yet, write your own, and use that instead of the default.

The actual part inside the method you'll need to change is pretty much what @mynameisbogdan and @SuperToma mentioned:

Remove the
`->andWhere('translation.locale = :locale')`
since it'll no longer be needed, and change
`->innerJoin('o.translations', 'translation', 'WITH', 'translation.locale = :locale')`
into
`->leftJoin('o.translations', 'translation')`.
and that should do the trick for this particular case (might cause other issues though, depending on which method is responsible).

Cheers 🍻

**Comment by bellu** [comment] 2024-04-19 02:04
@NoResponseMate i understand that load every translations could be resource-heavy. 

But i didn't customize anything, i installed some plugin, maybe one them i responsible of this situation.

Anyway i'm looking for the translation using straight the `ProductTranslation` entity and everything is working good.

👍
