### ISSUE TITLE
Expedition: Attempted to call an undefined method named "getLoadedMetadata" of class "Symfony\Component\VarDumper\Caster\CutStub".

### ISSUE THREAD

**Issue by taophp** [Sylius/Sylius#14881] opened 2023-03-22 15:47 UTC
**Sylius version affected**: 1.12.5

**Description**  
I just opened the "Expeditions" menu. It seems to work, but I get this exception à the end of the page.

**Steps to reproduce**  
Install a fresh instance of Sylius using Composer, log in the Back office and open the Expeditions menu.

**Comment by zchermit** [comment] 2023-04-18 06:53
The same issue. Sylius version: 1.12.17

**Comment by Rafikooo** [comment] 2023-04-21 11:04
Hello @zchermit ,
Thanks for submitting the issue. We tried to reproduce your case and did not see any exceptions. Can you please provide some additional information on how to achieve such error or a screenshot or even a short video that shows this? 
Thanks 💃

**Comment by zchermit** [comment] 2023-04-21 11:14
Hi @Rafikooo,  I logged in as admin and go to products. I used Symfony 6.2.8 and Sylius v1.12.7. Screenshop attahced.
![getLoadedMetadata](https://user-images.githubusercontent.com/3582430/233622481-7714dd94-0e14-4e00-b205-05625bafd3d2.PNG)

**Comment by Rafikooo** [comment] 2023-04-21 12:02
Hmm 🤔 Ok, so we will try again, thanks for a fast response

**Comment by zchermit** [comment] 2023-04-21 12:06
> Hmm 🤔 Ok, so we will try again, thanks for a fast response

Also I installed this plugin: friendsofsylius/sylius-import-export-plugin
Maybe something in there...

**Comment by coldic3** [comment] 2023-04-28 10:02
@zchermit Could you paste your `composer.json` and `composer.lock` so we'll be able to reproduce it 💃

**Comment by zchermit** [comment] 2023-04-28 11:14
> @zchermit Could you paste your `composer.json` and `composer.lock` so we'll be able to reproduce it 💃

**Additional information**: if I disable debug toolbar (config/packages/web_profiler.yaml) then all working good.
```
framework:
        profiler: 
            collect: false
```

**composer.json**
```
{
    "type": "project",
    "keywords": [
        "symfony",
        "sylius",
        "distribution",
        "ecommerce",
        "cart",
        "shopping"
    ],
    "homepage": "https://sylius.com",
    "license": "proprietary",
    "authors": [
        {
            "name": "Paweł Jędrzejewski"
        },
        {
            "name": "Sylius project"
        },
        {
            "name": "Community contributions"
        }
    ],
    "require": {
        "php": "^8.0",
        "ext-xmlreader": "*",
        "friendsofsylius/sylius-import-export-plugin": "^0.24.0",
        "gesdinet/jwt-refresh-token-bundle": "^1.1",
        "loevgaard/sylius-brand-plugin": "^2.2",
        "portphp/csv": "^2.0",
        "portphp/spreadsheet": "^1.0",
        "sylius/paypal-plugin": "^1.5",
        "sylius/sylius": "^1.12",
        "symfony/dotenv": "^5.4 || ^6.0",
        "symfony/flex": "^2.1",
        "symfony/runtime": "^5.4 || ^6.0",
        "synolia/sylius-maintenance-plugin": "*"
    },
    "require-dev": {
        "behat/behat": "^3.7",
        "behat/mink-selenium2-driver": "^1.4",
        "dmore/behat-chrome-extension": "^1.3",
        "dmore/chrome-mink-driver": "^2.7",
        "friends-of-behat/mink": "^1.8",
        "friends-of-behat/mink-browserkit-driver": "^1.4",
        "friends-of-behat/mink-debug-extension": "^2.0",
        "friends-of-behat/mink-extension": "^2.4",
        "friends-of-behat/page-object-extension": "^0.3",
        "friends-of-behat/suite-settings-extension": "^1.0",
        "friends-of-behat/symfony-extension": "^2.1",
        "friends-of-behat/variadic-extension": "^1.3",
        "lchrusciel/api-test-case": "^5.0",
        "phpspec/phpspec": "^7.0",
        "phpstan/extension-installer": "^1.0",
        "phpstan/phpstan": "^1.8.4",
        "phpstan/phpstan-doctrine": "^1.3.2",
        "phpstan/phpstan-webmozart-assert": "^1.1",
        "phpunit/phpunit": "^8.5",
        "polishsymfonycommunity/symfony-mocker-container": "^1.0",
        "stripe/stripe-php": "^6.43",
        "sylius-labs/coding-standard": "^4.0",
        "sylius/sylius-rector": "0.11.x-dev",
        "symfony/browser-kit": "^5.4 || ^6.0",
        "symfony/debug-bundle": "^5.4 || ^6.0",
        "symfony/intl": "^5.4 || ^6.0",
        "symfony/web-profiler-bundle": "^5.4 || ^6.0"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true,
        "allow-plugins": {
            "symfony/flex": true,
            "dealerdirect/phpcodesniffer-composer-installer": false,
            "phpstan/extension-installer": false,
            "symfony/thanks": false,
            "symfony/runtime": true
        }
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "^6.0",
            "endpoint": [
                "https://api.github.com/repos/Sylius/SyliusRecipes/contents/index.json?ref=flex/main",
                "flex://defaults"
            ]
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        },
        "classmap": [
            "src/Kernel.php"
        ]
    },
    "prefer-stable": true,
    "minimum-stability": "dev",
    "scripts": {
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ],
        "post-create-project-cmd": [
            "@php -r \"file_put_contents('.gitignore', str_replace('/composer.lock' . PHP_EOL, '', file_get_contents('.gitignore')));\"",
            "@php bin/console sylius:inform-about-gus --ansi",
            "@php bin/console sylius:show-available-plugins --ansi"
        ],
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        }
    },
    "replace": {
        "symfony/polyfill-apcu": "*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-intl": "*",
        "symfony/polyfill-intl-grapheme": "*",
        "symfony/polyfill-intl-icu": "*",
        "symfony/polyfill-intl-idn": "*",
        "symfony/polyfill-intl-normalizer": "*",
        "symfony/polyfill-mbstring": "*",
        "symfony/polyfill-php54": "*",
        "symfony/polyfill-php55": "*",
        "symfony/polyfill-php56": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*"
    }
}
```
**composer.lock** is to big (your comment is too long (maximum is 65536 characters))

**Comment by jakubtobiasz** [comment] 2023-05-02 05:00
Hi @zchermit 👋🏼!
I'm unable to reproduce the issue.

1) Try to run composer update to make sure your all dependencies are up-to-date
2) Try to create a fresh instance of Sylius with using Sylius-Standard
3) You can upload your `composer.lock` by changing its name to `composer.log` and dragging and drop on the GitHub's text editor area or by using https://gist.github.com

**Comment by Rafikooo** [comment] 2023-05-13 11:45
Hello @zchermit ,

Any updates? 💃

**Comment by zchermit** [comment] 2023-05-21 05:17
Hi @Rafikooo ,
Now I can't reproduce this problem either. Maybe it was some issue in my own code. Sorry for wasted your time. Thank you!

**Comment by jakubtobiasz** [comment] 2023-05-21 06:55
Hi @zchermit,
I'm glad to hear everything works now :). I'm closing this issue then, but please don't hesitate to ask for reopen or open a new one once a new bug occurs.

**Closed as completed by jakubtobiasz** 2023-05-21 06:55 UTC
Labels: Potential Bug
