### ISSUE TITLE
Sorting of attributes on product detail is not correct if there are more than 10 attributes

### ISSUE THREAD

**Issue by AndreasA** [Sylius/Sylius#11305] opened 2020-03-31 11:28 UTC
**Sylius version affected**: 1.4-1.7

**Description**  
The attributes on the Product detail page are sorted using the `SortByExtension` and then `attribute.position`. However, the `SortByExtension` only supports string comparison which means that after `10` attributes the sort order will be weird as e.g. `5` is higher than `15` in a string comparison.

See `SortByExtension` from line 52 (current master): https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UiBundle/Twig/SortByExtension.php#L52

And attributes listing (current master):
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Tabs/Attributes/_list.html.twig#L3

**Steps to reproduce**  
- Add over 10 attributes to Sylius and assign them to a product.
- Upon product detail page.
- Check ordering.

**Possible Solutions**  
- Use either the twig filter `sort` with an arrow function.
- Or: Add integer support to `SortByExtension`.

**Comment by vvasiloi** [comment] 2020-03-31 11:48
https://github.com/Sylius/Sylius/issues/10369
https://github.com/Sylius/Sylius/issues/10676

**Comment by pamil** [comment] 2020-04-07 10:12
Thanks for reporting, I'm closing it as it's a duplicate of #10676.

**Closed by pamil** 2020-04-07 10:12 UTC
Labels: Bug
