### ISSUE TITLE
[ContentBundle] Static page saving is broken

### ISSUE THREAD

**Issue by psyray** [Sylius/Sylius#2696] opened 2015-04-27 22:43 UTC
Hi,

Seems there is a problem with static content.

I'm experiencing a problem while saving static content with route or while saving route or while saving menu linked with static content.
Or in short while a CMS form use the ContentChoiceType form element.

The error is not exactly the same as @antonioperic in the #2682 issue, but I'm sure this is the same bug.

Problem is : 
I can't update a page if a route has been defined.
If no route, no problem. Tried to directly save a route and error ("This value is not valid").

After a Xdebug day :( I found that CMF save the static content linked with route using the id (eg: /cms/pages/test, generated by the ContentChoiceType choice list), but before saving the route content it makes a query in the document manager to check if a static page with the id exists, but in the document props (in mysql db table phpcr_nodes), there is no "sv:property" with "sv:name" : id.
If I create a node elsewhere in the props db field like this :
```
    <sv:property sv:name="id" sv:type="String" sv:multi-valued="0">
        <sv:value length="15">/cms/pages/test</sv:value>
    </sv:property>
```
no problem, route is correctly saved with linked content.

Maybe there is a modification in CMF that introduce a change in the way CMF documents are saved, and the ContentChoiceType form element need to be updated.
I searched an entire day without success. Maybe someone more experienced than me with Symfony can tell me where the bug is.

Does anyone can confirm this bug ?
- Can't save a static content with a route,
- Can't save a route with a linked static content,
- Can't save a menu element with a linked static content.

It's an annoying bug which break the CMS functionnality.
I will try to search & resolve this bug, but help is appreciated ;)

**Comment by nicolasricci** [comment] 2015-04-28 10:45
Yes I can confirm I have the same issue. I will have a look into this as well and let you know if I find anything.

**Comment by psyray** [comment] 2015-04-28 17:39
@nicolasricci Thx ;)

Here is the faulty PHPCR Mysql query
```
doctrine.DEBUG:
SELECT n0.id AS n0_id, n0.path AS n0_path, n0.parent AS n0_parent, n0.local_name AS n0_local_name, n0.namespace AS n0_namespace, n0.workspace_name AS n0_workspace_name, n0.identifier AS n0_identifier, n0.type AS n0_type, n0.props AS n0_props, n0.depth AS n0_depth, n0.sort_order AS n0_sort_order
FROM phpcr_nodes n0 
WHERE n0.workspace_name = ? 
AND n0.type IN ('nt:unstructured', 'rep:root') 
AND (EXTRACTVALUE(n0.props, 'count(//sv:property[@sv:name="id"]/sv:value[text()="/cms/pages/test"]) > 0') 
AND (EXTRACTVALUE(n0.props, 'count(//sv:property[@sv:name="phpcr:class"]/sv:value[text()="Symfony\\Cmf\\Bundle\\ContentBundle\\Doctrine\\Phpcr\\StaticContent"]) > 0') 
OR EXTRACTVALUE(n0.props, 'count(//sv:property[@sv:name="phpcr:classparents"]/sv:value[text()="Symfony\\Cmf\\Bundle\\ContentBundle\\Doctrine\\Phpcr\\StaticContent"]) > 0'))) ["default"] []
```
This query doesn't return anything because it search an inexistant id in the props field, and cause the "This value is not valid" error message.

**Comment by antonioperic** [comment] 2015-05-02 13:00
Is there any progress regarding this bug?

**Comment by psyray** [comment] 2015-05-04 07:20
Hi,
No progress, can't found what's wrong with PHPCR nodes ID....

**Comment by antonioperic** [comment] 2015-05-09 11:20
Maybe @dbu, @smith77 or @dantleech can help

**Comment by dantleech** [comment] 2015-05-09 11:40
Maybe an incorrect mapping somewhere? In the DBAL implementation the identifiers are kept in separate columns to the properties..

**Comment by dantleech** [comment] 2015-05-09 11:51
This seems to be the culprit:

````
at DocumentRepository->findBy(array('id' => array('/cms/pages/Dostava'))) in /var/www/sylius/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/Form/ChoiceList/EntityChoiceList.php line 224
    at EntityChoiceList->getChoicesForValues(array('/cms/pages/Dostava')) in /var/www/sylius/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php line 52
    at ChoiceToValueTransformer->reverseTransform('/cms/pages/Dostava') in /var/www/sylius/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 1105
    at Form->viewToNorm('/cms/pages/Dostava') in /var/www/sylius/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 632
    at Form->submit('/cms/pages/Dostava', true) in 
````

i.e. the DataTransformer is specifying `id`, which does not exist in PHPCR (it should use `DocumentManager#find(null, $id)` in this case).

Maybe @dbu knows something about this?

**Comment by dbu** [comment] 2015-05-10 09:12
this looks similar to the issue we struggle with in https://github.com/doctrine/DoctrinePHPCRBundle/pull/193 . somehow different symfony versions behave differently with regards to the form types. unfortunately i did not manage to dig to the root of the problems and am short on time to do that right now. but maybe this is a pointer for somebody?

**Comment by psyray** [comment] 2015-05-12 09:14
Thanks for your reply @dbu .
I tried to use different version of Symfony, same error.

I'm not experienced enough to find the solution.
If @dbu  do not manage to find, I do not see how I can be useful ...

I don't understand why, like you, without modify anything, the save failed.
A vendor must have changed in a certain way to produce this error.

**Comment by duanesteel** [comment] 2015-05-16 07:27
This was a big roadblock on a project I'm working on so I made this change for now. Seems to work for me, but not sure it would be a proper fix or just a hack to keep things moving. Although this is my first time using the ODM rather than the ORM it seems like the existing method was just plain broken. Let me know if my inexperience here is sending me barking up the wrong tree.

I made the following change:

In phpcr-bundle/Form/ChoiceList/PhpcrOdmQueryBuilderLoader.php changed getEntitiesByIds to:

    public function getEntitiesByIds($identifier, array $values)
    {
        $qb = clone $this->queryBuilder;
        $alias = $qb->getPrimaryAlias();
        
        foreach ($values as $val) {
            	$qb->orWhere()->same($val,'e');
        }
        return $this->getResult($qb);
    }

**Comment by psyray** [comment] 2015-05-17 18:33
Good catch !!
Your workaround is working.
But I think this should introduce another bug somewhere, because you're not using the identifier var which should be important.
Anyway this could help to unblock things before an official patch is released.

We should ask to @dbu what he is thinking about this.

**Comment by duanesteel** [comment] 2015-05-17 23:27
I forgot i left out the identifier was I was just testing different ideas. I think if we add back the identifier check it should still work the same and be a more complete solution.

**Comment by dantleech** [comment] 2015-05-18 05:36
I think the issue is that `id` does not exist, to query by the PHPCR `id` you must use the field `jcr:uuid`. So it might be that [the query builder converter](https://github.com/doctrine/phpcr-odm/blob/master/lib/Doctrine/ODM/PHPCR/Query/Builder/BuilderConverterPhpcr.php#L133) should handle this mapping (i.e. the designated `Id` field to `jcr:uuid`). @dbu wdyt?

**Comment by dbu** [comment] 2015-05-18 06:21
for phpcr-odm, the primary id of a document is the repository path to it. that is not a normal property ("column") but a core feature, so it needs no name. what value is passed for $identifier, "id"? the uuid dan is talking about is the other way of identifying a document regardless of its path. it is only available if a document is marked as being referenceable. luckily DocumentManager::findMany looks at the ids and handles both UUID and paths.

it looks like the fix in https://github.com/doctrine/DoctrinePHPCRBundle/pull/193 should indeed help for this problem. its not merged yet as the problem i originally tried to solve there was not solved by it. but that could be a different problem. i will have another look at this.

if you guys can try the fix-phpcr_document-formtype branch of DoctrinePHPCRBundle and report if it not only makes the error go away but also works as intended, that would be very helpful.

**Comment by psyray** [comment] 2015-05-18 07:46
I can confirm that the `fix-phpcr_document-formtype` branch fix the problem and work as intended.
Does anyone could confirm too ?

**Comment by nicolasricci** [comment] 2015-05-19 12:38
Yes this is fixing the issue. @dbu Let us know when this is merged to the DoctrinePHPCRBundle

**Comment by dbu** [comment] 2015-05-19 12:48
great, i will try to have a look at it again tonight.

**Comment by psyray** [comment] 2015-05-22 15:20
DoctrinePHPCRBundle fix released.
Update your vendor and it should be good.
https://github.com/doctrine/DoctrinePHPCRBundle/pull/193

**Comment by jeffsacco** [comment] 2015-05-22 15:40
Is anyone still having the issue when creating a "page" that when you visit the URL it says the route isnt found?

**Comment by pjedrzejewski** [comment] 2015-05-23 08:02
Fixed in #2763.

**Closed by pjedrzejewski** 2015-05-23 08:02 UTC
Labels: Bug

**Comment by jeffsacco** [comment] 2015-05-23 19:19
I have updated both symfony and phpcr to the respected values.  I create a new page and try to visit that url and cannot find the route.

Hoping someone might be able to offer me a little bit of guidance on this one

**Comment by jimbocoder** [comment] 2015-05-23 23:30
@jeffsacco you will probably need to re-init the CFM to get the main `/cms/routes` created correctly before adding routes.

**Comment by jeffsacco** [comment] 2015-05-24 01:34
@jimbocoder How might I reinitialize it?

**Comment by psyray** [comment] 2015-05-24 11:15
php app/console doctrine:phpcr:repository:init

**Comment by jeffsacco** [comment] 2015-05-24 12:15
@psyray I just ran that command and created a new page and still nothing.  Getting the no route error

**Comment by jeffsacco** [comment] 2015-05-24 12:24
Here is my output.  All went well.  Is there something I should check in the db?


![screen shot 2015-05-24 at 8 24 04 am](https://cloud.githubusercontent.com/assets/4239463/7787829/4cb40794-01ee-11e5-90f5-216cb984b46d.png)

**Comment by jeffsacco** [comment] 2015-05-24 12:32
Here is my db table for php cr

![screen shot 2015-05-24 at 8 32 20 am](https://cloud.githubusercontent.com/assets/4239463/7787853/76175752-01ef-11e5-8d74-e88b47657f66.png)

**Comment by jeffsacco** [comment] 2015-05-24 12:34
Now I know it works as I set up a fresh copy of standalone Sylius and I could visit the pages.  Just need to get my in development copy up and running.  Any help is greatly appreciated.

**Comment by jeffsacco** [comment] 2015-05-24 12:52
On a positive not, the taxonomy urls are working fine now :)

**Comment by jeffsacco** [comment] 2015-05-24 13:05
Here is something a little more interesting.  When I visit /content/test I get this error

![screen shot 2015-05-24 at 9 04 34 am](https://cloud.githubusercontent.com/assets/4239463/7787937/fbc5bc50-01f3-11e5-8d95-ab5066eb5f85.png)

**Comment by jeffsacco** [comment] 2015-05-24 13:14
Here is the code inside show.html.twig

![screen shot 2015-05-24 at 9 14 29 am](https://cloud.githubusercontent.com/assets/4239463/7787963/57bc7610-01f5-11e5-90ff-65ccec369dab.png)

**Comment by patkar** [comment] 2015-05-24 13:39
Please don't polute GitHub Issues with personal errors. Better create a new question on stackoverflow with sylius and symfony tags.

P.S.: Don't make screenshots of text, copy&paste it!

**Comment by jeffsacco** [comment] 2015-05-24 13:41
ok, Sorry about that.
