### ISSUE TITLE
Impossible to add media on a product ?

### ISSUE THREAD

**Issue by wyllyjon** [Sylius/Sylius#7875] opened 2017-04-01 10:41 UTC
Hello ! 

I don't know if I miss something as I didn't found any user doc on Sylius.org, but I can't see how to add media on a new product.
![media](https://cloud.githubusercontent.com/assets/26768253/24578017/6124eb16-16d8-11e7-8dbe-2d3845cfde10.png)
There is no button to add any media...

**Comment by TheMadeleine** [comment] 2017-04-03 08:35
![image](https://cloud.githubusercontent.com/assets/13198869/24601447/388750e0-1859-11e7-9738-ff125857af3b.png)

I can;t reproduce you issue. Maybe try `yarn install` and `yarn run gulp` once more?

**Comment by pjedrzejewski** [comment] 2017-09-12 08:06
Should be fixed now. I could not reproduce as well.

**Closed by pjedrzejewski** 2017-09-12 08:06 UTC
Labels: Potential Bug
