### ISSUE TITLE
php app/console sylius:install error

### ISSUE THREAD

**Issue by tuxado** [Sylius/Sylius#2351] opened 2015-01-18 03:38 UTC
I can't install sylius locally it appear there are a probleme with TranslatableListener when the Option model are loaded for creating mysql tables

string(42) "Sylius\Component\Attribute\Model\Attribut
string(40) "Sylius\Component\Product\Model\Attribute"
string(39) "Sylius\Component\Variation\Model\Option"

PHP Notice:  Trying to get property of non-object in C:\Symfony\sylius\src\Syliu
s\Bundle\TranslationBundle\EventListener\TranslatableListener.php on line 60

Notice: Trying to get property of non-object in C:\Symfony\sylius\src\Sylius\Bun
dle\TranslationBundle\EventListener\TranslatableListener.php on line 60
PHP Notice:  Trying to get property of non-object in C:\Symfony\sylius\src\Syliu
s\Bundle\TranslationBundle\EventListener\TranslatableListener.php on line 60

Notice: Trying to get property of non-object in C:\Symfony\sylius\src\Sylius\Bun
dle\TranslationBundle\EventListener\TranslatableListener.php on line 60
PHP Notice:  Trying to get property of non-object in C:\Symfony\sylius\src\Syliu
s\Bundle\TranslationBundle\EventListener\TranslatableListener.php on line 64

Notice: Trying to get property of non-object in C:\Symfony\sylius\src\Sylius\Bun
dle\TranslationBundle\EventListener\TranslatableListener.php on line 64

  [ReflectionException]
  Class  does not exist

any ideas how can i resolve this issue?

**Comment by mtthb** [comment] 2015-01-23 08:49
Probable duplicate of #2343

**Closed** 2015-02-16 08:03 UTC
