### ISSUE TITLE
My new theme isn't being loaded

### ISSUE THREAD

**Issue by teratux** [Sylius/Sylius#9522] opened 2018-06-25 18:03 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.3

Hi ... I'm currently trying to create a custom theme after reading the official documentation on how to do it.  I created an EventListener that I registered in my Kernel so that when the site loads I can select which theme I want to display.   The problem is that the new theme is not registering itself in the Sylius system, I'm using the full stack Sylius version, not a Symfony install that uses Sylius' bundles.

These are the files:
services.yml:
```
    Redbridge\EventListener\ThemeRequestListener:
        public: true
        autowire: true
        autoconfigure: true
        class: 'Redbridge\EventListener\ThemeRequestListener'
        arguments:
          - '@sylius.repository.theme'
          - '@sylius.theme.context.settable'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
```
src/EventListener/ThemeRequestListener.php:
```
<?php

namespace Redbridge\EventListener;

use Sylius\Bundle\ThemeBundle\Context\SettableThemeContext;
use Sylius\Bundle\ThemeBundle\Repository\InMemoryThemeRepository;
use Sylius\Bundle\ThemeBundle\Repository\ThemeRepositoryInterface;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\HttpKernelInterface;

class ThemeRequestListener
{
    /**
     * @var ThemeRepositoryInterface
     */
    private $themeRepository;

    /**
     * @var SettableThemeContext
     */
    private $themeContext;

    /**
     * @param ThemeRepositoryInterface $themeRepository
     * @param SettableThemeContext $themeContext
     */
    public function __construct( ThemeRepositoryInterface $themeRepository, SettableThemeContext $themeContext )
    {
        $this->themeRepository = $themeRepository;
        $this->themeContext = $themeContext;
    }

    /**
     * @param GetResponseEvent $event
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        if (HttpKernelInterface::MASTER_REQUEST !== $event->getRequestType()) {
            // don't do anything if it's not the master request
            return;
        }

        $this->themeContext->setTheme( $this->themeRepository->findOneByName('first_template') );
    }
}
```
app/themes/MyNewTheme/composer.json:
```
{
  "name": "first_template",
  "title": "A first Redbridge Template",
  "description": "A first Redbridge Template",
  "authors": [
    {
      "name": "Roberto Espi",
      "email": "teratux@gmail.com",
      "homepage": "http://kamil.kokot.me",
      "role": "Developer"
    }
  ]
}
```
config.yml:
```
sylius_theme:
    sources:
        filesystem: ~
```
When I run the command: $ bin/console sylius:theme:list I get:
`There are no themes.`

Any help would be appreciated
Thanks ...

**Comment by teratux** [comment] 2018-06-27 18:46
Bump? ... I've followed every guide I've found, the official docs, and similar issues shown here that are related even to not clearing the cache but still nothing.

**Comment by CoderMaggie** [comment] 2018-06-29 09:51
@teratux I believe what you are missing is the `sylius-theme` part of you theme's composer.json file.
http://docs.sylius.com/en/latest/book/themes/themes.html#how-to-create-themes
![image](https://user-images.githubusercontent.com/13198869/42086199-ae905762-7b92-11e8-9632-a1bd1ec63ede.png)


Please next time before opening issue make sure it is a real bug, as for support requests we use either our [Forum](https://forum.sylius.com/) or [Slack](http://sylius.com/slack) :)

**Comment by teratux** [comment] 2018-06-29 16:54
Ok I'll move the thread over there.  I included the extra section with the sylius-theme part but still no results, the same problem.

**Comment by teratux** [comment] 2018-06-29 19:46
Interesting, I managed to solve the problem making changes in the order I included my services.  This is the original 
```
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }
    - { resource: "services.yml" }
    - { resource: "parameters.yml" }
    - { resource: "security.yml" }
```
and the changed config.yml:
```
    - { resource: "services.yml" }
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }
    - { resource: "parameters.yml" }
    - { resource: "security.yml" }
```

Now Sylius complained that the name for the themes don't match the regex expression for their title.  Changed them, and all done.  Any idea on what happened here?

**Comment by ehibes** [comment] 2018-10-04 08:52
@CoderMaggie It seems to be a bug between [symfony 4 flex structure and Sylius 1.3](https://sylius-devs.slack.com/archives/C3EGDG9LY/p1537981168000100).
Can you reopen the issue?

**Comment by pamil** [comment] 2020-04-07 11:22
Tried to reproduce it but it looks fixed in the most recent Sylius distribution, feel free to open a new one if that's still a case.

**Closed by pamil** 2020-04-07 11:22 UTC
Labels: Bug
