### ISSUE TITLE
Multiple carts on the same user

### ISSUE THREAD

**Issue by Duderis** [Sylius/Sylius#9859] opened 2018-10-25 12:53 UTC
**Sylius version affected**: 1.3.1

**Description**  
If you somehow manage to get two orders in state of cart for the same user, it behaves weirdly and potentially dangerously.

**Steps to reproduce**  
(tried it out on demo to make sure its not due to local edits)
Add any item to cart, proceed to checkout, sign in with the email form during the address step, clear site data from browser (i imagine this to replicate somebody accessing the store from two different computers), go back to clean homepage, add a different item and proceed to checkout, now during the cart summary you see the correct item, but once you fill in the sign in form in the addressing step, the item changes back to the first item (from the previous cart (also noticed in database (local) that the new cart doesn't get assigned with a customer)).

**Possible Solution**  
No code solution, but probably a simple solution would be to clear previous orders in cart state associated with the user that is trying to get added to the cart (this is what I'll be trying to do on our shop).

**Comment by pamil** [comment] 2018-11-12 14:49
Duplicate of #8370, let's keep the discussion there.

**Closed by pamil** 2018-11-12 14:49 UTC
Labels: Potential Bug
