### ISSUE TITLE
[SyliusResourceBundle]: Call to a member function addPrefix() on null

### ISSUE THREAD

**Issue by nietzscheson** [Sylius/Sylius#7799] opened 2017-03-21 21:20 UTC
I'm using SyliusResources v1.0.0-beta.1 on Symfony 3.2. I followed the [documentation](http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/) to create resources. All good, even when I have needed to exclude some of the routes of the resource:
```yml
app_admin_user:
    resource: |
        alias: app.user
        section: admin
        except: ['delete', 'update']
        redirect: update
    type: sylius.resource
```
It throws me the following:
```
FatalThrowableError in YamlFileLoader.php line 148:
Call to a member function addPrefix() on null```

**Comment by pamil** [comment] 2017-03-23 17:41
I can't reproduce it on master, are you sure that Sylius is causing the issue? Can you provide a stacktrace?

**Comment by pjedrzejewski** [comment] 2017-03-23 19:16
@nietzcheson Please reopen if you reproduce it on master.

**Comment by lchrusciel** [comment] 2017-03-23 22:05
Not sure if relevant, but the snippet above is wrong
```yml
        except: ['delete', 'update']
        redirect: update
```
We cannot declare redirect to the route which is excluded from routeing generation.

**Comment by inspiran** [comment] 2017-05-19 20:24
@pamil and @pjedrzejewski  , when updating to latest master I am facing the same issue.

at YamlFileLoader->parseImport(object(RouteCollection), array('resource' => 'alias: sylius.admin_usersection: adminpath: userstemplates: SyliusAdminBundle:Crudexcept: [\'show\']redirect: indexgrid: sylius_admin_admin_userpermission: truevars: all: subheader: 


If I remove the         except: ['show']   from   the sylius_admin_admin_user route, the error goes away.  Hope this helps tracking the issue down.

**Comment by lchrusciel** [comment] 2017-05-20 16:19
Reopening then.

**Comment by nietzcheson** [comment] 2017-05-22 18:03
I had this bug ... I tried several ways to fix it. The last solution I gave was to delete vendors and update all packages ... Everything works ...

**Comment by pjedrzejewski** [comment] 2017-09-12 07:02
^ closing then.

**Closed by pjedrzejewski** 2017-09-12 07:01 UTC
Labels: Potential Bug
