### ISSUE TITLE
Promotion Flash Messages

### ISSUE THREAD

**Issue by bretto36** [Sylius/Sylius#5968] opened 2016-09-03 05:32 UTC
Whenever i add a promotion to the cart i get a number of messages that are unnecessary. On thank you page i'll get 3 flashes saying the same thing 
![capture2](https://cloud.githubusercontent.com/assets/6217994/18222960/dbc48310-71ea-11e6-9807-33ab76f62ecc.PNG)

When adding the promotion to the cart i seem to get an invalid message for all other coupon based promotions even though i didn't try and add them![capture3](https://cloud.githubusercontent.com/assets/6217994/18222970/666616c8-71eb-11e6-84fd-e77edefed332.PNG)

If i remove one of the promotions from the channel i get 1 less error message

**Comment by bretto36** [comment] 2016-09-03 05:44
Made a pull request for the last issue. 

Not sure how to fix first issue

**Comment by tchapi** [comment] 2016-09-05 10:47
I have the same behaviour, thanks for this PR, hope it will be merged soon !

**Comment by pjedrzejewski** [comment] 2016-09-05 14:57
Duplicate of #5008.

**Closed by pjedrzejewski** 2016-09-05 14:57 UTC
