### ISSUE TITLE
An exception has been thrown during the rendering of a template (“”) in @SyliusShop\Product\Show\_inventory.html.twig at line 4

### ISSUE THREAD

**Issue by yosriMekni** [Sylius/Sylius#6532] opened 2016-10-24 14:15 UTC
i have this exception :

An exception has been thrown during the rendering of a template ("") in @SyliusShop\Product\Show_inventory.html.twig at line 4. 500 Internal Server Error - Twig_Error_Runtime 1 linked Exception: NotFoundHttpException »

and this is the file that throws the exception : ShopBundle/Resources/views/Product/Show/_inventory.html.twig:

```
`{% if product.simple and not sylius_inventory_is_available(product.firstVariant) %}
{% include '@SyliusShop/Product/Show/_outOfStock.html.twig' %}
```

{% else %}
    {% render(url('sylius_shop_cart_item_add', {'template': '@SyliusShop/Product/Show/_addToCart.html.twig', 'productId': product.id})) %}
{% endif %}`
ShopBundle/Resources/config/routing/cart.yml:

`sylius_shop_cart_item_add:
path: /add
methods: [GET, POST]
defaults:
    _controller: sylius.controller.cart_item:addAction
    _sylius:
        factory:
            method: createForProduct
            arguments: [expr:service('sylius.repository.product').find($productId)]
        form:
            type: sylius_cart_item
            options:
                product: expr:service('sylius.repository.product').find($productId)
        template:  $template
        redirect:
            route: sylius_shop_cart_summary
            parameters: {}
        flash: sylius.cart.item_add_completed`
i make sure that the product id is not null , what can be the problem ?
issue on stackoverflow : http://stackoverflow.com/q/40216966/5092143

**Comment by yosriMekni** [comment] 2016-10-24 15:01
is there any way to fix it ?

**Comment by michalmarcinkowski** [comment] 2016-12-01 22:59
Looks like the product with this ID doesn't exist. Closing as it's not a bug.

**Closed by michalmarcinkowski** 2016-12-01 22:59 UTC
