### ISSUE TITLE
"php app/console sylius:install" throw Exception

### ISSUE THREAD

**Issue by sruj** [Sylius/Sylius#5982] opened 2016-09-05 18:32 UTC
Hi, I follow Sylius installation guide step by step and encounter Exception 

> chiny@chiny-EP35-DS3R:/var/www/html/acme$ sudo php app/console sylius:install
> [sudo] hasło użytkownika chiny: 
> Installing Sylius...
> 
> Step 1 of 4. Checking system requirements.
> Success! Your system can run Sylius properly.
> 
> Step 2 of 4. Setting up the database.
> Creating Sylius database for environment dev.
> It appears that your database already exists. Would you like to reset it? (y/N) y
>  7/7 [||||||||||||||||||||||||||||] 100%
> Warning! This will erase your database. Your current environment is dev.
> Load sample data? (y/N) y
> Loading sample data...
> Created "web/media/" directory.
> Created "web/media/image/" directory.
>  0/1 [|                           ]   0%
>                                                            
>   [Symfony\Component\Debug\Exception\FatalThrowableError]  
>   Call to a member function getCode() on null              
>                                                            
> 
> sylius:fixtures:load [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> [<suite>]
> 
> chiny@chiny-EP35-DS3R:/var/www/html/acme$

**Comment by tchapi** [comment] 2016-09-05 18:39
Hi @sruj , I guess this is a duplicate of https://github.com/Sylius/Sylius/issues/5762, you might want to close this issue and subscribe to the main one ;)

**Closed** 2016-09-05 18:40 UTC
