### ISSUE TITLE
If a user logined , redirect to last page if he opens the login page again

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#6705] opened 2016-11-14 09:41 UTC
The reason why I create this issue is that in Sylius design, a user might login our system using LinkedIn for example,  or using password , It is not reasonable that a logined user can use a another password account to login  without logout, so I suggest  we add a redirection  if he opens the login page again.

**Comment by pjedrzejewski** [comment] 2016-11-14 09:54
Duplicate of https://github.com/Sylius/Sylius/issues/3448.

**Closed by pjedrzejewski** 2016-11-14 09:54 UTC
