### ISSUE TITLE
Composer dependency fails for doctrine/phpcr-odm

### ISSUE THREAD

**Issue by Buri** [Sylius/Sylius#3595] opened 2015-11-20 12:35 UTC
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package doctrine/phpcr-odm could not be found in any version, there may be a typo in the package name.
  Problem 2
    - sylius/sylius dev-master requires doctrine/phpcr-odm ^1.3@rc -> no matching package found.
    - sylius/sylius dev-master requires doctrine/phpcr-odm ^1.3@rc -> no matching package found.
    - Installation request for sylius/sylius dev-master#08f24fe -> satisfiable by sylius/sylius[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by pjedrzejewski** [comment] 2015-11-20 12:37
@Buri What version Sylius? Which command for install?

**Comment by Buri** [comment] 2015-11-20 12:40
dev-master#08f24fe, composer update

**Comment by PWalkow** [comment] 2015-11-20 12:41
@pjedrzejewski same here, same problem while composer update:
doctrine/phpcr-odm ^1.3@rc -> no matching package found.

**Comment by mojzis** [comment] 2015-11-20 12:59
I think the [minimum stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) will have to be set to RC, in composer.json, otherwise it wont work.

**Comment by Buri** [comment] 2015-11-20 13:14
Adding `"minimum-stability":"RC"` to project fixes the issue, but you should probably add it to your composer too.

**Comment by pamil** [comment] 2015-11-20 14:06
It's weird that it does work for me and for Travis, isn't `minimal-stability` affected by some global configuration? We require `doctrine/phpcr-odm` in `^1.3@rc` and `phpspec/phpspec` in `^2.4@alpha` versions in order to support PHP7.

**Comment by mojzis** [comment] 2015-11-20 14:28
i think the problem is when you require sylius such as from [Sylius-Standard](https://github.com/Sylius/Sylius-Standard)

**Comment by pamil** [comment] 2015-11-20 14:48
In that case the one who require Sylius should have to modify `minimal-stability` and `prefer-stable`. As for `Sylius/Sylius-Standard`, we should also update `travis.yml` not to use PHP 5.3 / 5.4 and use PHP 5.6 / 7.0 instead.

**Comment by pamil** [comment] 2015-11-23 13:27
Just sent a PR #3609 that changes minimum stability from `alpha` to `rc`.

**Comment by pjedrzejewski** [comment] 2015-11-26 00:59
@Buri Could you check if this problem is gone? Please close the issue if true, thanks! :)

**Closed** 2015-11-26 14:19 UTC
