### ISSUE TITLE
Cannot override TaxonTranslation without Taxon (same for Taxonomy)

### ISSUE THREAD

**Issue by fr-systeme** [Sylius/Sylius#2884] opened 2015-06-17 09:13 UTC
i want to override TaxonTranslation but a bad line of code force me to override Taxon too.
```protected function getTranslationClass()
{
    return get_class().'Translation';
}```
in Sylius\Component\Taxonomy\Model\Taxon ... get_class() get the complete namespace -> Sylius\Component\Taxonomy\Model\TaxonTranslation and not mine. :(

its the same in Taxonomy + the constructor  has a bad line of code
``` $this->setRoot(new Taxon()); ``` in Sylius\Component\Core\Model\Taxonomy

if i subclass Taxon it will init every time Sylius\Component\Core\Model\Taxon and not mine
```
// this is how i solve this problem ... not very sexy 
 public function __construct()
{
        //parent::__construct();
        $this->translations = new ArrayCollection();
        $this->setRoot(new Taxon());
} 
```
maybe its better to call a override able method in the constructor and not set the TaxonObject direct.
``` 
protected function initRootTaxon()
{
     $this->setRoot(new Taxon());
}
```

i only want to override TaxonTranslation but I ended up with 4 subclassed models.

**Comment by pjedrzejewski** [comment] 2015-12-09 16:00
Duplicate of #3480.

**Closed by pjedrzejewski** 2015-12-09 16:00 UTC
Labels: DX
