### ISSUE TITLE
[BUG] Pagination Doesn't Work Properly

### ISSUE THREAD

**Issue by tugrulgencoglu** [Sylius/Sylius#12861] opened 2021-08-04 13:30 UTC
**Sylius version affected**: 1.10.0 (latest)

**Description**  

Pagination limits does not work. Let say your product limit is n, in page 1 shows n-2 products and page 2 shows n-1 products and like so. It's not about my configuration or something you can clearly see this bug in sylius demo ( https://demo.sylius.com/en_US/taxons/category?page=1 )

**Steps to reproduce**  

Just follow the installation guideline on documentation (here: https://docs.sylius.com/en/latest/getting-started-with-sylius/installation.html )
Install with sample data.
Visit page 1 ( here: http://localhost/en_US/taxons/category?page=1 )
Visit page 2 ( here: http://localhost/en_US/taxons/category?page=2 )
...
**Possible Solution**

**Comment by vvasiloi** [comment] 2021-08-04 14:13
Possible duplicate of https://github.com/Sylius/Sylius/issues/10343

**Comment by CoderMaggie** [comment] 2021-09-09 20:07
Could you confirm if this bug still exists @tugrulgencoglu?
It might've been fixed after this 👉🏼  https://github.com/Sylius/SyliusGridBundle/pull/68

**Comment by gencoglutugrul** [comment] 2021-09-09 21:40
I checked it with clean installation and yes problem fixed! 
Thanks for your works.

**Closed** 2021-09-20 16:17 UTC
Labels: Potential Bug
