### ISSUE TITLE
[BC break][1.9][API] Non Sylius routes are broken

### ISSUE THREAD

**Issue by stloyd** [Sylius/Sylius#12152] opened 2020-12-09 17:24 UTC
**Sylius version affected**: 1.9.x

**Description**  
If you have own routes defined as API-Platform ones, in 1.9-dev those are broken due too new `PathPrefixProvider`.

~~If you have `prefix` for routes, even Sylius ones, those will not work either anymore.~~

**Steps to reproduce**  
Create own entity with `@ApiResource`:
```php
/**
 * @ApiResource(
 *     collectionOperations={},
 *     itemOperations={
 *         "get"={
 *             "security"="is_granted('ROLE_ADMIN') or object == user",
 *         },
 *     }
 * )
 *
 * @ORM\Entity
 */
class SomeClass
```
Call this new endpoint as logged-in: 500, due too mismatch of predefined prefixes vs no prefix.

**Possible Solution**  
Change in `RouteNameResolver`:

```php
    private function returnMatchingRouteName(
        array $matchingRoutes,
        string $operationType,
        string $resourceClass
    ): string {
        if (count($matchingRoutes) === 1) {
            return array_key_first($matchingRoutes);
        }

        foreach ($matchingRoutes as $routeName => $route) {
            $routePrefix = $this->pathPrefixProvider->getPathPrefix($route->getPath());
            if ($routePrefix === null) {
                return $routeName;
            }

            $requestPrefix = $this->pathPrefixProvider->getCurrentPrefix();
            if ($requestPrefix === $routePrefix) {
                return $routeName;
            }
        }

        throw new InvalidArgumentException(
            sprintf('No %s route associated with the type "%s".', $operationType, $resourceClass)
        );
    }

**Comment by stloyd** [comment] 2020-12-09 17:33
Also it's broken if:
- your user is admin calling API that is not Sylius one,
- you extend Sylius entity and overwrite any endpoint,

**Comment by stloyd** [comment] 2020-12-31 18:20
@lchrusciel @pamil This is critical BC break that broke whole support of Sylius in version 1.9, and as there will be soon alpha release can we revert the broken part or try too prioritise the potential fix?

**Comment by stloyd** [comment] 2021-01-24 07:53
@pamil This is critical BC break that broke whole custom support of Sylius in version 1.9, we have now alpha 2 release, can we revert the broken part or try too prioritise the potential fix?

I proposed some workaround in description , but it still was not enough for our custom api resources...

**Comment by lchrusciel** [comment] 2021-01-28 10:24
Hey @stloyd,

thanks for reminding us about this issue. It is in our backlog and should be fixed before the 1.9 release.

**Comment by GSadee** [comment] 2021-03-02 06:54
Hi @stloyd! I would really like to reproduce the problem so that we can fix it, but I am probably missing something important in your description. Could you explain one more time what is the actual problem? Because I've tried to reproduce the case from your description and I've got the 500, but not because of predefined prefixes but because that route is not under the firewall and it looks like the correct behaviour at first glance. I'm also not 100% sure how to recreate the cases you wrote in your first comment.

**Comment by GSadee** [comment] 2021-03-04 10:46
I'm closing this issue for now, as we introduced a test application in ApiBundle with some basic tests for overwriting the configuration. 

Associated PRs:
https://github.com/Sylius/Sylius/pull/12329
https://github.com/Sylius/Sylius/pull/12410
https://github.com/Sylius/Sylius/pull/12416
https://github.com/Sylius/Sylius/pull/12411

In one of the PRs, I recreated the problem that needed your proposed solution.

We've added also a note in our docs about paths: https://github.com/Sylius/Sylius/pull/12412

Of course, @stloyd, feel free to reopen that issue or add another one with specific problems.

**Closed by GSadee** 2021-03-04 10:46 UTC
Labels: Bug
