### ISSUE TITLE
web profiler does not work

### ISSUE THREAD

**Issue by kiakahaDZ** [Sylius/Sylius#13424] opened 2021-12-28 10:26 UTC
**Sylius version affected**: 1.10

**Description**  
An error occurred while loading the web debug toolbar.
Return value of Symfony\Component\HttpKernel\DataCollector\MemoryDataCollector::getMemoryLimit() must be of the type int, float returned

![image](https://user-images.githubusercontent.com/46278484/147556586-22cff6f9-fe04-4e59-b303-87854f7fdeaf.png)

**Steps to reproduce**  
Just Install Sylius And Start the dev server and you will get the error 

**Possible Solution**  
I have seen on the main Symfony GitHub that an issue was solved for this subject and this is the ticket 
https://github.com/symfony/symfony/pull/44809

**Comment by jakubtobiasz** [comment] 2021-12-28 12:29
It seems to be a Symfony's bug itself. Can you tell me what's your value of `memory_limit`? This error is related with converting the `memory_limit` value to bytes. I've tried to reproduce this error but on my side everything is working properly.

**Comment by kiakahaDZ** [comment] 2021-12-28 12:33
@jakubtobiasz thinks for the response, `memory_limit = 2G` and also i tried `memory_limit = 128M` i use windows 64 bits.

**Comment by Zales0123** [comment] 2021-12-28 12:43
Hello @kiakahaDZ 🖖 Thank you for the report, but as @jakubtobiasz says, it's definitely not a Sylius specific bug. If it was fixed in Symfony, I'm sure a new patch version will be released soon :)

**Closed by Zales0123** 2021-12-28 12:43 UTC

**Comment by kiakahaDZ** [comment] 2021-12-28 12:45
@Zales0123 thinks for the response but sylius built on symfony hope that doesn't take much time and the composer update does the job if it's fixed by symfony right?

**Comment by jakubtobiasz** [comment] 2021-12-28 12:48
Symfony hasn't released the fix yet. Try setting `memory_limit` to values such `256M`, `512M` or `-1`. On macOS every value except `128M` is working with the fresh sylius installation. Unless Symfony release the next version including the fix Sylius team can't do anything with it.

**Comment by kiakahaDZ** [comment] 2021-12-28 12:51
okay, I will wait for the new version of Symfony, I tried different values for the `memory_limit` but the problem doesn't solve.
